### ISSUE TITLE
Running the core from command line crashes the emulator on Windows, while running within the GUI doesn't

### ISSUE THREAD

**Issue by Drakonas** [GLupeN64/GLupeN64#101]
I am trying to set up GLupeN64 to be used via command line on Windows but when I do, it crashes and a black screen shows behind the "has stopped working" window.

Here's my verbose log, with no error shown that I could see: http://pastebin.com/yFTnaqW1

The roms run fine when I load the core via the RetroArch GUI instead of command line.

**Comment by loganmc10** [comment]
A couple questions:

Does this happen with mupen64plus-libretro?

Do you get the core from the libretro buildbot or the buildbot that I run?

**Comment by Drakonas** [comment]
No this crash doesn't happen with mupen64plus-libretro via command line. I tried both the libretro Core updater version and the binary builds from this Github. Both crash.

**Comment by Awakened0** [comment]
The latest win64 build from the buildbot linked on this git still launches fine from my Steam shortcuts and by pasting the command line I use in those into a command prompt:

> "F:\Blue\Emulation\Emulators\RetroArch\retroarch.exe" -L Cores\glupen64_libretro.dll "F:\Blue\Emulation\Games\Nintendo 64\Super Smash Bros. (USA).7z"

**Comment by loganmc10** [comment]
I won't have access to a Windows machine to test this on until Monday. It looks like it's crashing around the time it would b trying to write the mupen64plus.ini file to disk, maybe there is some kind of file permission issue and it can't write the file?

Anyway I'll test on Monday but I think I've successfully launched a game from the command line in Windows before

**Comment by Drakonas** [comment]
I have RetroArch in a directory unaffected by permissions issues. At least to my knowledge. RetroArch is in a custom made directory in my C drive that doesn't need administrator to make/edit files.

**Comment by loganmc10** [comment]
I can't reproduce this, launching a game from the command line seems to work fine for me on Windows.

**Comment by Drakonas** [comment]
Should I be using stable 7-16 RetroArch build or Nightly?

**Comment by loganmc10** [comment]
Either one should work.

**Comment by Drakonas** [comment]
Visual Studio Debuggers shows this exception: "0xC0000005: Access violation reading location 0x0000000000000028"

**Comment by loganmc10** [comment]
Ya I'm not really a Windows guy so it's hard to say. Maybe it's the anti virus blocking some kind of access? You could try deleting the GLupeN64 folder inside your RetroArch system dir (the directory should contain "mupen64plus.ini", "GLideN64.custom.ini", and a "shaders" folder), delete all that, including the GLupeN64 folder and then try starting from the command line.

**Comment by loganmc10** [comment]
I assume it has something to do with file writing because the last line in the log is:

> RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: ....

Which is what it would print right before writing/reading a file, but my assumption could be wrong

**Comment by loganmc10** [comment]
I suppose it could be an issue with save memory as well, you could try moving/deleting the .srm file associated with the game you are trying to launch, although you would think you would have an issue whether you launched via the GUI or the command line.

**Comment by Drakonas** [comment]
I'll try those things after my memtest. I will note that memtest86 so far is reporting possible row hammer bit flip vulnerability, which is an apparently common of RAM sticks newer than 2010.

**Comment by Drakonas** [comment]
Apparently something in the retroarch.cfg was causing it. Not sure what exactly. But renaming the file and having the emulator regenerate it fixed my issue.

Here's my original config in alphabetical order (making it easier to compare): http://pastebin.com/NGQGHY2i

Here's the replaced config: http://pastebin.com/py9tqN7a

I see a few things which may have caused the issue. If you want me to look into it I will, and I can report back to you, but I figure something in the config file may give an indicator to you what the problem is.

**Comment by Drakonas** [comment]
Lol it was the first thing I tried:

        audio_filter_dir = ":\filters\audio"
should be this:
        audio_filter_dir = ":\filters/audio"

Not sure what caused it but now we know.
