### ISSUE TITLE
Linux/radeonsi flashing, garbled faces with HLE on radeonsi

### ISSUE THREAD

**Issue by BPaden** [GLupeN64/GLupeN64#102]
if I load an n64 from with glupen, the faces just twist around like crazy and flash. LLE works, but it's very slow. I've uploaded a screenshot of the weridness. This issue isn't present with llvmpipe (which is actually faster than LLE)

 so it may be an issue with radeonsi. I'm using nightly git builds of mesa, and I don't get any output from mesa with MESA_DEBUG=1

This issue manifests both in the most recent git commit of retroarch, and retroarch 1.3.6. I'm using the most recent nightly build of glupen, and I also tried a build of the depth branch, but ran into the same issue. This doesn't appear to be related to #70 and isn't effected by toggling framebuffer emulation.

[I've uploaded an apitrace to google drive](https://drive.google.com/open?id=0B3fzbAhRSFcbNXBmVy1wQ1ZJUjQ)

Here's the log I see when replaying it:

[retroarch-replay.txt](https://github.com/loganmc10/GLupeN64/files/587458/retroarch-replay.txt)

**Comment by loganmc10** [comment]
What version of Mesa is this?

**Comment by BPaden** [comment]
I use mesa-git, but I can confirm the issue is present in mesa 13.0.0.

**Comment by loganmc10** [comment]
Hm ok I'll look at the apitrace in a bit, where is the screenshot that you took?

**Comment by BPaden** [comment]
Here's the intro to the legend of zelda :)

![screenshot from 2016-11-12 12-35-00](https://cloud.githubusercontent.com/assets/1188012/20243078/279fa22a-a90d-11e6-9bb6-224de1019e7d.png)

**Comment by loganmc10** [comment]
I can't actually replay the trace on my laptop since it's an old Intel laptop and only supports GL 3.3

Can you post the output of glxinfo? I assume this might be because of some incompatibility with one of the GL extensions we use (ARB_buffer_storage, ARB_texture_storage, ARB_draw_indirect)

Doea this happen with mupen64plus-libretro?

**Comment by loganmc10** [comment]
You could also try building with DEBUG=1 in the Makefile, since it uses a slightly different method for buffer mapping, but the fact that it works in LLE mode is strange

**Comment by loganmc10** [comment]
Sorry one other thing to try would be to disable indirect drawing by forcing this line to false:

https://github.com/loganmc10/GLupeN64/blob/master/GLideN64/src/OpenGL.cpp#L2336

ie comment out that line and add
```
use_indirect=false
```

**Comment by BPaden** [comment]
use_indirect=false does work (DEBUG=1 does not), but it's even slower in that case than LLE.

This issue does not exist with mupen64plus-libretro (though on that core, I get a broken rupee display in LoZ). I recently tested mupen64plus+gliden64, and with that setup the rendering is completely black.

Note that, according retroarch, glupen is using an OpenGL 3.3 core profile.

[glxinfo.txt](https://github.com/loganmc10/GLupeN64/files/587610/glxinfo.txt)

**Comment by loganmc10** [comment]
If use_indirect=false fixes it and it works with LLE all the time then it is likely that the driver has an issue with glDrawElementsIndirect, on Monday I'll try and get in contact with the radeonsi devs to discuss this, but I don't think any other drivers have this issue so I assume something might be broken with the driver

**Comment by loganmc10** [comment]
I've submitted a bug report with Mesa:

https://bugs.freedesktop.org/show_bug.cgi?id=98724

**Comment by loganmc10** [comment]
@BPaden Can you create an apitrace with DEBUG=1 set (everything else the same as master)? apitrace doesn't support some features that GLupeN64 uses in release mode, but it will work with DEBUG=1.

**Comment by loganmc10** [comment]
Also, could you create a trace using llvmpipe as well? (the radeonsi people are asking for this so they can do their troubleshooting)

**Comment by loganmc10** [comment]
@BPaden Any update on this? Is it still happening with the latest version of Mesa?

**Comment by BPaden** [comment]
Looks to still be happening, unfortunately. From the other bug discussion, I think it's a firmware issue, so not something that can likely be fixed easily. I'm OK with closing this bug if you want, unless you can think of a workaround since it's not likely to be a glupen64 bug.

It's interesting that I don't see this with other software, though. Is the indirect extension not commonly used? Or is it likely there is something special in the way glupen64 us interacting with the driver that my hardware doesn't like?

**Comment by loganmc10** [comment]
The indirect extension probably isn't commonly used. From my testing I don't see any noticeable difference without it so I think I'll just remove it (ec2f51088ebb110ee27f7b1b6e51673c5dd48d18).

Can you try the latest master?

**Comment by BPaden** [comment]
Hmm, it does work for me, but not at a playable framerate.

It could be that my gpu is simply not fast enough to handle glupen64's approach to emulation, or it could be that the indirect extension was used as a performance optimization. I don't know much of anything about graphics programming (my math-fu is weak), so I couldn't say.

I would ask around to see if anyone on a lower end card noticed any performance regressions.

**Comment by loganmc10** [comment]
I don't think it will be accurate to compare broken indirect drawing with working normal drawing. The indirect drawing on your card wasn't drawing much at all, so it's not surprising that it was fast.

I'm not sure why it's so slow on your card, I have a relatively old Intel GPU (only supports OpenGL 3.3) and most games run at full speed, I've never heard from anyone on a laptop/desktop that they can't get a playable frame rate on Ocarina of Time, even most lower end Android phones can handle that title

**Comment by loganmc10** [comment]
Ok the original problem is solved so I'll close this, the garbling etc is all good. I'm not sure why you have performance issues, I have been testing this on my laptop and a Shield Tablet, and there are a good number of Raspberry Pi users as well, which has a fairly weak GPU, and it works reasonably well, especially a game like Ocarina of Time, so I'm not sure what's up there
