### ISSUE TITLE
Instability caused by PBO code

### ISSUE THREAD

**Issue by loganmc10** [GLupeN64/GLupeN64#106]
This commit:

https://github.com/GLupeN64/GLupeN64/commit/298c49fcb5d94879e41fc9af619ea9113a5351f9

Has introduced some instability, I can't get the core starting in Windows anymore (crashes). It seems to work fine in Linux for the most part, but even there I've run into a few random crashes, I've not been able to get a backtrace.

If anyone is able to get a backtrace from a crash (or even an apitrace so I can see where it dies) it would be very helpful. This shouldn't affect most mobile devices since they won't use PBO's unless they support ARB_buffer_storage.

**Comment by loganmc10** [comment]
I'm curious if anyone else is experiencing this problem. I was having issues in Windows and Linux inside VMware, but I don't see any issues on regular Linux with Intel or Nvidia drivers

**Comment by orbea** [comment]
What games have you tried it with? Super Smash Bros seems to work correctly for me in Slackware, I was able to complete classic without a problem.

**Comment by loganmc10** [comment]
On Windows it crashed instantly for me every time, every game. Inside VMware it would randomly crash after maybe 3-5 minutes of play, but every time I tried to run it in debug mode with gdb I could never trigger it.

The VMware mesa drivers are crappy in general and I've had random issues with them in the past, but I'm curious if the Windows build works for anyone else, maybe I need to update the Nvidia drivers there

**Comment by Awakened0** [comment]
Everything crashes for me instantly on windows with the latest build too. I updated my Nvidia drivers a few days ago (using the version before the hotfix that was just released). Backtrace: http://hastebin.com/suqidohota.tex

**Comment by loganmc10** [comment]
I think I've been able to reproduce a part of this problem on Linux, Works Armageddon crashes on launch for me...

**Comment by orbea** [comment]
I guess this issue is related. https://github.com/GLupeN64/GLupeN64/issues/109

**Comment by Awakened0** [comment]
I run at default res though, so it's not the higher res that's causing it for me.

**Comment by loganmc10** [comment]
It's all related to the new PBO code, it's essentially a faster way to upload textures to the GPU, I must be calculating the size of the textures incorrectly so it is writing/reading outside a valid buffer

**Comment by loganmc10** [comment]
@Awakened0 I think I may have fixed this, but I don't have access to my Windows machine to test, you can try the latest build to check http://loganbuildbot.s3-website-us-east-1.amazonaws.com/

**Comment by Awakened0** [comment]
Crash is fixed, but now I get a black screen with working sound. When I pull up XMB the background gradient is replaced with blackness, but the ribbon and text still appear.
