### ISSUE TITLE
(Suggestion) Create gliden64.log in the system/GLupeN64 directory

### ISSUE THREAD

**Issue by orbea** [GLupeN64/GLupeN64#110]
Just a small suggestion to have the gliden64.log file created in the system/GLupeN64 directory. It might be nice to have a consistent place for that to be found.

**Comment by loganmc10** [comment]
This is actually a GLideN64 thing:

https://github.com/GLupeN64/GLupeN64/blob/master/GLideN64/src/Log.h#L29

It just creates the file in the current directory. If it used the mupen64plus API to get the directory then GLupeN64 would put it in the right folder.

I believe the function that it would need to use is called GetUserDataPath().

You'll notice that mupen64plus does the same thing.

Anyway I would file an issue with GLideN64 and ask that it use GetUserDataPath() to determine the path to put the file.

**Comment by orbea** [comment]
I did not realize that, I made the suggestion as seen in the referenced issued. You can close this if you think best or we can wait for the response in the upstream issue?

**Comment by orbea** [comment]
Seems like gonetz obliged. :)

https://github.com/gonetz/GLideN64/commit/1c94b4720ebcb7bfaa9e76cc744b6f6b004c494e

**Comment by loganmc10** [comment]
Yep that was fast, I'll close this when I get a chance to merge it

**Comment by orbea** [comment]
I checked, this is being created in the correct directory now. :)
