### ISSUE TITLE
Binary Builds inaccessable

### ISSUE THREAD

**Issue by tony971** [GLupeN64/GLupeN64#111]
"Error: [object Object]"

It's been going on for a week or two now.

**Comment by loganmc10** [comment]
I just opened it in incognito mode and downloaded one and it worked. Is anyone else having this issue?

**Comment by tony971** [comment]
Found the problem: https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/?src=ss

**Comment by loganmc10** [comment]
I guess since the URL is an Amazon URL it expects it to be SSL encrypted. I would need to pay for an SSL certificate for that, so you'll need to add an exception or something.

**Comment by orbea** [comment]
Usually https-everywhere will use http if https is available and only run into this if https is available and not configured properly. Is there a way you can just turn off https more thoroughly? That may solve it.

**Comment by loganmc10** [comment]
I believe the purpose of https everywhere is to protect against attacks like this: https://moxie.org/software/sslstrip/

Basically when your browser connects to amazon.com, it doesn't know if the connection is supposed to be HTTP or HTTPS. If an attacker could "man-in-the-middle" the connection, they can present to you a version of amazon.com without HTTPS, thus reading your username/password, they then establish an HTTPS connection with amazon.com and pass along your username/password, so everything looks normal to you. So amazon.com thinks it has a proper HTTPS connection, and your browser thinks it has a proper HTTP connection.

HTTPS everywhere maintains a list of websites that are supposed to be HTTPS, so when you visit, and it's HTTP, it refuses the connection. My buildbot is hosted on amazon.com, but it's not HTTPS, they don't offer that service for S3 buckets as far as I'm aware.

**Comment by orbea** [comment]
Ah, that makes sense. I guess that might just make people using https-everywhere have to find a work around like you said.

**Comment by loganmc10** [comment]
I would assume that the HTTPS-Everywhere plugin allows you maintain a list of exceptions, but I don't use it so I don't know for sure.

**Comment by tony971** [comment]
I just disabled the extension for Amazon Web Services. Feel free to close the issue.

**Comment by loganmc10** [comment]
Ok I'll close it, if anyone knows how to use SSL with an S3 bucket or knows of some better service to use to host the builds I'm open to it
