### ISSUE TITLE
Weird Textures in Goldeneye

### ISSUE THREAD

**Issue by jaburgeson** [GLupeN64/GLupeN64#112]
There appears to be weird textures in Goldeneye that do not appear using standard GLideN64.

Screenshot below!

<img width="1395" alt="screen shot 2016-11-21 at 9 00 54 pm" src="https://cloud.githubusercontent.com/assets/4240091/20508187/d704392a-b02d-11e6-82b9-ef34eafa3103.png">
<img width="1395" alt="screen shot 2016-11-21 at 9 01 08 pm" src="https://cloud.githubusercontent.com/assets/4240091/20508188/d70ea284-b02d-11e6-8deb-ba9bf4b24cee.png">

**Comment by loganmc10** [comment]
Can you post your retroarch-core-options.cfg as well as some system specs? (OS, graphics card)

**Comment by jaburgeson** [comment]
I am running Windows 10.  Intel i7 6700k with a GTX 1080 and 16gb of Memory.

Here is the config

glupen64-169screensize = "320x180"
glupen64-aspect = "4:3"
glupen64-BilinearMode = "3point"
glupen64-MultiSampling = "0"
glupen64-EnableFBEmulation = "True"
glupen64-EnableCopyAuxiliaryToRDRAM = "True"
glupen64-EnableCopyColorToRDRAM = "Sync"
glupen64-EnableCopyDepthToRDRAM = "FromMem"
glupen64-EnableCopyColorFromRDRAM = "False"
glupen64-EnableHWLighting = "False"
glupen64-CorrectTexrectCoords = "Off"
glupen64-EnableNativeResTexrects = "False"
glupen64-EnableLegacyBlending = "False"
glupen64-txFilterMode = "None"
glupen64-txEnhancementMode = "None"
glupen64-txHiresEnable = "False"
glupen64-astick-deadzone = "15"
glupen64-pak1 = "memory"
glupen64-pak2 = "memory"
glupen64-pak3 = "none"
glupen64-pak4 = "none"

**Comment by loganmc10** [comment]
Ok should be fixed now, thanks for reporting this! Let me know if it's fixed for you.

**Comment by jaburgeson** [comment]
It is fixed!

Thanks Logan!
