### ISSUE TITLE
Ship a build on Ubuntu PPA

### ISSUE THREAD

**Issue by Nine-H** [GLupeN64/GLupeN64#113]
What it says in the title: I would like a build committed to the ubuntu PPA, for linux x86 and x86_64.

**Comment by orbea** [comment]
@sergiobenrocha2 Are you building or willing to build GLupeN64 for your PPA?

**Comment by Nine-H** [comment]
not sure about a couple of the specifics of debian packaging but I could. bit it seems silly for me to do it while there are official libretro PPAs:

https://launchpad.net/~libretro/+archive/ubuntu/stable
https://launchpad.net/~libretro/+archive/ubuntu/testing

**Comment by sergiobenrocha2** [comment]
Not yet, I can add next week.

**Comment by sergiobenrocha2** [comment]
what's the version of this core btw? same as mupen, 2.0 ?

**Comment by sergiobenrocha2** [comment]
I'm making the debian package right now. Man, why we have this:

```
# Raspberry Pi
else ifneq (,$(findstring rpi,$(platform)))
   TARGET := $(TARGET_NAME)_libretro.so
   LDFLAGS += -shared -Wl,--version-script=$(LIBRETRO_DIR)/link.T -Wl,--no-undefined
   GLES = 1
   GLSL_OPT = 1
   CPUFLAGS += -DVC
   ifneq (,$(findstring mesa,$(platform)))
      GL_LIB := -lGLESv2
   else
      GL_LIB := -L/opt/vc/lib -lGLESv2
      INCFLAGS += -I/opt/vc/include
   endif
   WITH_DYNAREC=arm
   ifneq (,$(findstring rpi2,$(platform)))
      CPUFLAGS += -mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard
      HAVE_NEON = 1
   else ifneq (,$(findstring rpi3,$(platform)))
      CPUFLAGS += -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard
      HAVE_NEON = 1
   endif

# ODROIDs
else ifneq (,$(findstring odroid,$(platform)))
   TARGET := $(TARGET_NAME)_libretro.so
   LDFLAGS += -shared -Wl,--version-script=$(LIBRETRO_DIR)/link.T -Wl,--no-undefined
   BOARD := $(shell cat /proc/cpuinfo | grep -i odroid | awk '{print $$3}')
   GLES = 1
   GL_LIB := -lGLESv2
   CPUFLAGS += -marm -mfloat-abi=hard -mfpu=neon
   HAVE_NEON = 1
   WITH_DYNAREC=arm
   ifneq (,$(findstring ODROIDC,$(BOARD)))
      # ODROID-C1
      CPUFLAGS += -mcpu=cortex-a5
   else ifneq (,$(findstring ODROID-XU3,$(BOARD)))
      # ODROID-XU3 & -XU3 Lite
      ifeq "$(shell expr `gcc -dumpversion` \>= 4.9)" "1"
         CPUFLAGS += -march=armv7ve -mcpu=cortex-a15.cortex-a7
      else
         CPUFLAGS += -mcpu=cortex-a9
      endif
   else
      # ODROID-U2, -U3, -X & -X2
      CPUFLAGS += -mcpu=cortex-a9
   endif
```

It's all unix/linux after all. I cleaned up one or 2 makefiles cores in the libretro repo

**Comment by sergiobenrocha2** [comment]
Fine, done with the packaging.

Recipe: https://code.launchpad.net/~libretro/+recipe/glupen64-libretro-daily

It'll be published in the testing PPA soon (amd64 and i386 packages only for now)

**Comment by loganmc10** [comment]
The core doesn't really have a version, it just follows git, it also follows the git version of mupen64plus.

As for the complicated Makefile, I agree that the ARM stuff could probably be simplified, but I only have a Raspberry Pi, so I don't want make changes to the Makefile that I can't test for the other platforms, I'd accept a pull request if someone wants to simplify it.

They do need to be a little different though, the Raspberry Pi has it's own libraries in /opt/vc that need to be linked/included

**Comment by orbea** [comment]
At slackbuilds.org I use the date and hash of the last commit as the version. That seems to work well enough.

Example: `GLupeN64-2016.10.12_4378f48`

**Comment by sergiobenrocha2** [comment]
The source in launchpad doesn't have git stuff :)

It's showing GLupeN64 OpenGL only in the launchpad build. I put 2.0 in the debian packaging

**Comment by loganmc10** [comment]
Sure, 2.5 might be a little more accurate since the latest release of mupen64plus is 2.5, but even that doesn't really mean much

**Comment by sergiobenrocha2** [comment]
humm, does mupen core really up to date / sync with upstream? It received a bunch of backports, but I think it's more like 2.0. At least it's the official number in the core.

**Comment by loganmc10** [comment]
Ya the mupen64plus-libretro core doesn't keep up to date with upstream, they'll backport things when they see a need but they are not trying to keep it the same, in fact I believe they intend to deviate even further from mupen64plus in the future.

This core tracks mupen64plus, it is kept in sync and should function pretty much the exact same as the upstream version.

**Comment by loganmc10** [comment]
So can this be closed then? It's been added to the PPA right?

**Comment by sergiobenrocha2** [comment]
Yup
