### ISSUE TITLE
[Intel] Graphic glitches in Kirby

### ISSUE THREAD

**Issue by sergiobenrocha2** [GLupeN64/GLupeN64#115]
Intel:

![kirby 64 - the crystal shards usa -161125-032848](https://cloud.githubusercontent.com/assets/5431285/20615297/80cdb150-b2bf-11e6-839e-fef24c9d20b3.png)

Nvidia:

![kirby 64 - the crystal shards usa -161125-033110](https://cloud.githubusercontent.com/assets/5431285/20615316/b001224a-b2bf-11e6-9a96-0ae8e59ea458.png)

RSP Mode: HLE
4:3 resolution: 960x720

**Comment by loganmc10** [comment]
If you are able, can you run it with DEBUG=1 using the Intel driver and look for any GL errors in the output, similar to what your other issue had, something like:

```
GL_INVALID_OPERATION in glMapBufferRange(buffer already mapped)
```

**Comment by loganmc10** [comment]
By the way, when you say Nvidia, do you mean Mesa or the closed source driver?

**Comment by sergiobenrocha2** [comment]
Humm, nothing about GL. I can see stuff like:

```
intelReadPixels: fallback to CPU mapping in PBO case

Unsupported form of variable indexing in FS; falling back to very inefficient code generation

Recompiling fragment shader for program 34

  renderbuffer height 1024->480
```

**Comment by sergiobenrocha2** [comment]
I said Nvidia because I have that optimus technology, I can switch between Nvidia and Intel here, using bumblebee. Nvidia driver is 340.98:

```
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 4.3.0 NVIDIA 340.98
OpenGL core profile shading language version string: 4.30 NVIDIA via Cg compiler
OpenGL version string: 4.4.0 NVIDIA 340.98
OpenGL shading language version string: 4.40 NVIDIA via Cg compiler
```

**Comment by sergiobenrocha2** [comment]
Maybe it's another issue.

Trying to use LLE, effects like fire from sword and that white thing is behind the scene. Testing with Nvidia:

![kirby 64 - the crystal shards usa -161125-033644](https://cloud.githubusercontent.com/assets/5431285/20615482/a80b937a-b2c1-11e6-8632-a9ff3b555df9.png)

Same issue with Intel.

**Comment by loganmc10** [comment]
Does the intro to Super Smash Bros look normal on the Intel driver?

**Comment by sergiobenrocha2** [comment]
The smoke and electricity is quite buggy with intel

Intel:

![super smash bros usa -161125-043026](https://cloud.githubusercontent.com/assets/5431285/20616250/0b7624ec-b2c8-11e6-958d-c86d5039d802.png)

![super smash bros usa -161125-043112](https://cloud.githubusercontent.com/assets/5431285/20616258/1873525a-b2c8-11e6-9259-4bc20bb8f9bd.png)

Nvidia:

![super smash bros usa -161125-043237](https://cloud.githubusercontent.com/assets/5431285/20616284/47d5517e-b2c8-11e6-9ab1-3f4f29ab67c2.png)

**Comment by sergiobenrocha2** [comment]
The intro

![super smash bros usa -161125-043633](https://cloud.githubusercontent.com/assets/5431285/20616359/d0b9065c-b2c8-11e6-8993-c531d0cad81f.png)

**Comment by loganmc10** [comment]
I thought so, this is an issue with Mesa:

https://github.com/GLupeN64/GLupeN64/wiki/GPU-driver-tips

Updating Mesa will fix this issue. It is because of this bug: https://bugs.freedesktop.org/show_bug.cgi?id=95164

**Comment by orbea** [comment]
How involved would it be to get the mesa maintainer(s) for ubuntu to backport this fix?

**Comment by loganmc10** [comment]
I'm not sure about that, enabling "Less accurate blending mode" in the core options may work around this issue since it may avoid the problematic code, but I'm not 100% sure

**Comment by sergiobenrocha2** [comment]
Less accurate blending mode = ON seems to fix the first issue with Intel

**Comment by loganmc10** [comment]
OK I updated the Wiki with information about the blending mode work around. Anyway this is basically a graphics driver bug that has been fixed in recent version of Mesa, so besides posting information about the work around I don't think there is much I can do.

**Comment by sergiobenrocha2** [comment]
Ok, thanks!
