### ISSUE TITLE
High-res textures don't show

### ISSUE THREAD

**Issue by cascardian** [GLupeN64/GLupeN64#117]
First of all, thank you for implementing my initial request!

I finally found the time to test my texture packs. They sadly don't work, neither the HTCs nor pure PNGs. 

The interesting thing is that the packs are loaded, but the textures simply don't show. In the previous issue, I wrote "The usual options necessary to make some texture packs work (Full Alpha Channel usage, Alternate CRC etc.) would probably also be needed". I suspect this might be why.

For a good-looking _Super Mario 64_ pack to confirm, look for [Hypatia's MarioCraft](http://onthegreatsea.tumblr.com/DOWNLOADS). This pack, for instance, needs the Full Alpha Channel and 'Save texture cache to disk' (which would generate an HTC out of the PNGs) options to be set, as per readme. Without at least the former option ported over, the packs using full alpha channels, which should be [most of them](http://www.emutalk.net/forums/126-High-Resolution-Textures) these days, won't show.

Cheers!

**Comment by loganmc10** [comment]
Ok I added the Full Alpha Channel option with this commit: ef1ec72a5610af1c866eaba33e40ee483924a473

It's building right now so wait about 10 minutes if you're going to grab it from the buildbot.

Save texture cache to disk is the default so I'll leave that like it is. When I first implemented this I tested it with a high res pack for Super Mario and it works, I just tested it again and it still worked, so it seems to still be working (besides whatever options might need to be set)

Let me know if you need any other options besides Full Alpha Channel

**Comment by cascardian** [comment]
Thank you again, everything I have works perfectly now. Good work! If no one else has any packs that don't work, then I think this particular issue is dealt with for now.
