### ISSUE TITLE
[Kirby] Lack of effects using LLE

### ISSUE THREAD

**Issue by sergiobenrocha2** [GLupeN64/GLupeN64#123]
Trying to use LLE, effects like fire from sword and that white thing is behind the scene. Testing with Nvidia:

![kirby 64 - the crystal shards usa -161125-033644](https://cloud.githubusercontent.com/assets/5431285/20653220/119dc84a-b4f1-11e6-9f3b-bd9d45de3805.png)

Same issue with Intel.

With HLE it works fine, at least on nvidia.

**Comment by loganmc10** [comment]
I'll need to verify whether this happens with upstream GLideN64, there is a chance it's just a bug with GLideN64, it's not super great at LLE stuff at the moment

**Comment by sergiobenrocha2** [comment]
It may be related to https://github.com/libretro/mupen64plus-libretro/issues/155, but there it was an issue happening with GFX = glide64 and RSP = HLE

**Comment by loganmc10** [comment]
This looks like it's a GLideN64 issue. I tested upstream mupen64plus, and with HLE, when I "suck", you can see stuff getting sucked into Kirby's mouth (plus the wind). With LLE you only see the wind, no stuff.

I'll get screenshots of both situations and file an issue with GLideN64

**Comment by loganmc10** [comment]
Ok I filed an issue here:

https://github.com/gonetz/GLideN64/issues/1267

I'm going to close this since it is actually an issue with GLideN64
