### ISSUE TITLE
can't bind control stick to keys.

### ISSUE THREAD

**Issue by Nine-H** [GLupeN64/GLupeN64#124]
you can't use remap in the quick menu to bind the analog stick to a keyboard, you can only bind it's axes not UDLR.

**Comment by loganmc10** [comment]
This is probably something to bring up with RetroArch (https://github.com/libretro/RetroArch). That is the application that handles all the key mapping.

You might be able to get help on their forums (https://libretro.com/forums/) or their IRC channel as well (#retroarch on Freenode)

**Comment by Nine-H** [comment]
I was under the impression that cores returned a list of controller buttons and axes that would be used in a core or game remap file, for example if you open a neo-geo emulator it only lets you rebind UDLR, ABCD buttons, coin slot, and player start. If I was mistaken please close this issue, I just noted that you could bind c buttons or a c axis and I thought it sucked that I couldn't do the same with analog, I'm happy to report the bug to the libretro team, just let me know.

**Comment by orbea** [comment]
Someone recently in #retroarch mentioned that they were able to do this in mupen64plus-libretro by manually binding them in the config file rather than the RA menu. Regardless this seems like RetroArch issue than core issue.

**Comment by orbea** [comment]
This seems related. https://github.com/libretro/RetroArch/issues/4083

**Comment by orbea** [comment]
`RetroArch-2016.11.27_d6ebd2a_master-x86_64-1_git`

Actually I tried this again and it seems to have been fixed.

@Nine-H Could you try a RetroArch nightly and see if that works?

**Comment by loganmc10** [comment]
I'm going to close this since it is a RetroArch issue and it seems to be fixed

**Comment by Nine-H** [comment]
hey, sorry, I've been busy with work and other commitments for a couple of days.

the problem isn't that there's no way to rebind the control stick, it's that the proper way (binding n64 buttons to abstracted retropad ones) doesn't work, check in quickmenu > controls

**Comment by loganmc10** [comment]
This is possible in the regular RetroArch controller config, but you're asking for it to be available in the core remap options, do I understand that right?

**Comment by Nine-H** [comment]
yeah mate. sorry for the confusion.

**Comment by loganmc10** [comment]
K I'll have to look at the code a bit and probably talk to Twinaphex about it, I'm sure it's possible. The input code for this core was ripped directly from mupen64plus-libretro, so I've never looked at it very closely.

**Comment by Nine-H** [comment]
legend. thanks mate.

**Comment by orbea** [comment]
I'm not sure I follow, what would the use case for this be? Wouldn't binding them to the keyboard in the RetroArch input settings be enough?

**Comment by Awakened0** [comment]
It's because the C-Buttons are mapped to the right retropad analog and you can't remap stuff on the analogs using quick menu, controls yet. I have to manually remap them by changing how the retropad is mapped to my pad using game override configs for certain games.

**Comment by orbea** [comment]
I'm still not sure I follow. Using the input settings I can remap the right retropad analog (c-buttons) to both controller buttons and the keyboard and then successfully use these new binds with GLupeN64 and Ocarina of Time.

My understanding is that input settings are part of the frontend and not the core?

**Comment by Awakened0** [comment]
That's true as far as I know. The inability to remap anything on analogs through quick menu, controls is a limitation of the core/game remap system at the frontend level. Doing it through settings, input, user binds works around it since that hard remaps the retropad to different inputs on a pad. Quick menu, controls changes how the core maps inputs to retropad.

**Comment by loganmc10** [comment]
Yes I believe this is something that would need to be changed with RetroArch, there is an option in the quick menu to remap the "Control Stick X" and "Control Stick Y", but the only options are analog options, not keyboard keys or buttons.

There is nothing I can do to change that, they are defined as types RETRO_DEVICE_ID_ANALOG_X and RETRO_DEVICE_ID_ANALOG_Y, and it's up to RetroArch to define what options are available for remapping those types of inputs.

**Comment by Nine-H** [comment]
is there any way to define "Control Stick UpDownLeftRight" as digital buttons separate from "Control Stick XY" emulator side? I noticed that there's a C-axis but the C-up and C-left buttons are also keybindable from the quick menu.

On another note, can C-down and C-right be added as digital buttons and the C-Buttons-Mode button be removed: I don't know exactly what the mode button does, but it appears to press C-right and bind retropad X and Y to C-up and C-left. Confusing as! Just have them as straightforward binds and let users figure out what they want with the core and game remap features.

**Comment by loganmc10** [comment]
Most of this can be done in the core options, for instance you can look at how to map C buttons here:

https://github.com/libretro/mupen64plus-libretro/issues/319#issuecomment-215238903

I believe RetroArch allows you to save a core specific retroarch.cfg? I've never tried it but I've heard people say it can be done. It seems like that would be a good way to accomplish all this.

**Comment by loganmc10** [comment]
I've looked into this, there is no way for the core to offer this option currently. You have to set this up in the RetroArch options, there is no other way.
