### ISSUE TITLE
[Linux] Failed build with clang

### ISSUE THREAD

**Issue by sergiobenrocha2** [GLupeN64/GLupeN64#125]
Tried to use clang 3.6 and 3.8:

```
./GLideN64/src/GLideNHQ/TxQuantize.o:(.rodata+0x0): multiple definition of `Five2Eight'
./GLideN64/src/convert.o:(.rodata+0x0): first defined here
./GLideN64/src/GLideNHQ/TxQuantize.o:(.rodata+0x20): multiple definition of `One2Eight'
./GLideN64/src/convert.o:(.rodata+0x46): first defined here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [glupen64_libretro.so] Error 1
```

**Comment by loganmc10** [comment]
I submitted a pull request to fix this with GLideN64

https://github.com/gonetz/GLideN64/pull/1269

You are likely going to run into some other issues with clang once that gets sorted out though (https://github.com/mupen64plus/mupen64plus-core/issues/195)

**Comment by loganmc10** [comment]
It might work with x86/x86_64 though, the issues I had were specific to arm
