### ISSUE TITLE
San Francisco Rush 2049 shows black screen

### ISSUE THREAD

**Issue by jaburgeson** [GLupeN64/GLupeN64#126]
This game does not load, only shows a black screen.

This is with LLE and HLE enable with everything else set to default.

It works with the standard mupen64 core as well was Gliden64  plugin with project64

**Comment by orbea** [comment]
This is an upstream issue with mupen64plus + GLideN64 and I have reported it upstream as seen in the referenced issue.

**Comment by loganmc10** [comment]
@jaburgeson When was the last time you tried it with project64? GLideN64 recently changed a few of the default options, specifically "EnableCopyDepthToRDRAM" now defaults to "Software", where it used to be off before.

Can you try it with:
EnableCopyDepthToRDRAM = Off
EnableCopyColorToRDRAM  = Off

I'll try it in a bit if I get a chance

**Comment by orbea** [comment]
It will work with `EnableCopyColorToRDRAM = Off`.

**Comment by loganmc10** [comment]
hm then there might be something wrong with GLupeN64's reading of the GLideN64.custom.ini file, it should be doing that automatically:

https://github.com/GLupeN64/GLupeN64/blob/master/GLideN64/ini/GLideN64.custom.ini#L97-L99

upstream mupen64plus doesn't make use of that file (but Project64 does), so it's not surprising that it doesn't work with mupen64plus

**Comment by loganmc10** [comment]
Should be fixed by d1b7e1dede4581bf7018eb4c35d0fb8001d3eac2

**Comment by jaburgeson** [comment]
It will work with EnableCopyColorToRDRAM = Off. 

This did resolve the issue.  I will update to the latest binary and test out the fix logan.

**Comment by orbea** [comment]
This now works for me in GLupeN64, thanks!

**Comment by jaburgeson** [comment]
Works for me now as well!  Thanks Logan
