### ISSUE TITLE
GLES3 texture corruption

### ISSUE THREAD

**Issue by loganmc10** [GLupeN64/GLupeN64#130]
Screenshots of the issue are here:

https://github.com/GLupeN64/GLupeN64/issues/127#issuecomment-264178897

I believe this is because of some issue/incompatibility with EXT_buffer_storage

**Comment by loganmc10** [comment]
@fzurita I just tested this on a Shield Tablet and all the textures look correct, do you think your device could have some bug related to EXT_buffer_storage? (Given that it also has an issue with it with the debug setting as well)

**Comment by fzurita** [comment]
It's possible. We will see if the Nougat update fixes it. It will come with newer drivers.

**Comment by loganmc10** [comment]
@fzurita can you test this again when you get a chance? (just update the core on the RetroArch Online Updater), it might be fixed now

**Comment by fzurita** [comment]
Sure, I'll check.

**Comment by fzurita** [comment]
It seems fixed in Super Mario 64 and Conker.

Conker still has some issues that may be unrelated. Shadows are flickering. And Conker is still running very slowly. 

Shadows could be fixed of you allow configuring the polygon offset factor.

**Comment by loganmc10** [comment]
I'm not a big fan of cryptic options like "polygon offset factor", especially since RetroArch doesn't give me anywhere inside the application to explain what the options do. I'd rather have a hard-coded list in the application with the "best" polygon offset factor for each GPU, but I don't have the resources/access to devices to compile that list.

I'm not sure about the speed in Conkers, when I compared the frame rates between this and mupen64plus-ae they didn't seem very different, I think the audio stretching in AE really helps, I even played with the ViRefresh stuff and it didn't seem to make any difference, so I'm not sure what can be done there.

**Comment by fzurita** [comment]
Hmmm, interesting. I should going by FPS numbers. Maybe it's a problem specific to my GPU. Using 300% speed, I can reach 35-45fps in Conker using mupen64plus-ae. With GLupeN64, I'm only reaching about 25fps in-game.

I'm going to grab your branch of GLideN64 and run it using mepen64plus-ae and see if I get the same smoke downs

**Comment by fzurita** [comment]
I think this issue can be closed though. Original issue is fixed.
