### ISSUE TITLE
glCopyImageSubData not working on Android

### ISSUE THREAD

**Issue by loganmc10** [GLupeN64/GLupeN64#131]
A recent change (96a9e0e3f2c4915257278121d47cfb9ceae0fdae) has allowed glBlitFramebuffer calls to be replaced by glCopyImageSubData (GLES3 and OpenGL).

This works on OpenGL (Linux and Windows), and GLES3 mode in Mesa, but for some reason I get a black screen on my phone.

If someone (@orbea?) could test the latest nightly RetroArch Android app, and the latest build from my buildbot (at least 96a9e0e3f2c4915257278121d47cfb9ceae0fdae), I'm curious if this is an issue with my phone, or a general issue on Android.

I've tried plugging my phone in to grab a logcat, but I can't manage to see any errors, it all looks normal in the logcat for me.

Game to test ***Super Smash Bros GLES3***, not all games will produce a black screen, but this one will.

**Comment by orbea** [comment]
I tried compiled the latest master (96a9e0e3f2c4915257278121d47cfb9ceae0fdae) with GLES3 for android and found no new problems with my phone, Super Smash Bros still works. I am using an older nightly though from a month or two ago.

**Comment by loganmc10** [comment]
Do you have framebuffer emulation enabled?

**Comment by orbea** [comment]
Yes.
