### ISSUE TITLE
No Pill in Dr. Mario

### ISSUE THREAD

**Issue by jaburgeson** [GLupeN64/GLupeN64#132]
I had this issue with GlideN64 with Project64 as with it not loading the custom.ini file.

Not sure what the deal is with Glupen.

The pill doesn't show up in game which makes it hard to play!

All settings are default.

**Comment by loganmc10** [comment]
This is a really strange one, it works for my on my phone, and it works for me on Linux, but it doesn't work on Windows. Windows has a lot of strange flickering and missing pills.

But the really strange thing is that it works for me with mupen64plus on Windows...

**Comment by loganmc10** [comment]
So it turns out this was somehow related to the compiler optimizations that were used, should be fixed by 1fb0ea134256d322f07047bf9ab322d6c7d17227

You can try the latest version from my buildbot to be sure: http://loganbuildbot.s3-website-us-east-1.amazonaws.com/

**Comment by jaburgeson** [comment]
It is fixed!  Thanks again logan.
