### ISSUE TITLE
Config File for certain Games

### ISSUE THREAD

**Issue by Papermanzero** [GLupeN64/GLupeN64#133]
Currently GlideN64 can only work with global settings, if it is used as plugin in Mupen64Plus.
Compared to Project64 no game specific settings can be created (custom ini file).
To increase the compatibility it would be convenient to implement the custom ini file.

Related:
https://github.com/gonetz/GLideN64/issues/660

**Comment by loganmc10** [comment]
GLupeN64 uses GLideN64.custom.ini, I'd there is a setting in there it will override the user's setting

**Comment by orbea** [comment]
It is only mupen64plus that doesn't implement it for GLideN64. See here.

https://github.com/mupen64plus/mupen64plus-core/issues/217
