### ISSUE TITLE
Add LLE to Config File

### ISSUE THREAD

**Issue by jaburgeson** [GLupeN64/GLupeN64#136]
Since we have the ability to add games to the custom config files now, what is the parameter to use LLE instead of HLE.

I would like to set the default as HLE, but some games require LLE usage like Rogue Squadron and Indiana Jones.

**Comment by jaburgeson** [comment]
Nevermind, RetroArch actually allows you to do this in the Options menu of the Core if you have Load Content-Specific Core Options Automatically enabled in the Configuration menu in the settings enabled.

You can great Per-Game Core Configuration files that will load automatically.

**Comment by loganmc10** [comment]
Ya the core option is called "glupen64-rspmode" and the options are "HLE" or "LLE"

**Comment by loganmc10** [comment]
Oh did you mean something that would happen automatically? GLideN64.custom.ini can't control whether a game runs in HLE or LLE, there is currently no ini file that keeps track of that sort of thing, it needs to be set by the user

**Comment by jaburgeson** [comment]
Hi Logan, I did initially mean that! However, with that option enabled in Settings and the Game Specific .opt file that gets created it does happen automatically now.

Which is pretty cool.  You can create this for any game using any core and it will get loaded automatically.
