### ISSUE TITLE
Worms Armageddon - Cropped Screen Aspect and Slow Fade

### ISSUE THREAD

**Issue by Enverex** [GLupeN64/GLupeN64#146]
Two issues with Worms Armageddon (this was tested on an Odroid XU4 so it's using GLES).

Firstly is that the screen appears to be 16:9 but is cropped to 4:3 so you can't see the edges (they're just black).

Second is that emulation speed is fine, except for when it fades in and out of a game (e.g. at the end of a match), at which point it slows down to about 0.5fps.

**Comment by loganmc10** [comment]
Are you able to provide a screenshot of the cropping issue? I'm not really sure what you mean

**Comment by Enverex** [comment]
It's Lakka on an ARM board so god knows how I'd screen shot it. I'll draw it instead though to explain. 5 mins.

**Comment by Enverex** [comment]
Basically it looks like this, like it's drawing it at 16:9 and cropping it to 4:3 aspect, leaving the game cut-off with just black where the rest should be.

![image](https://cloud.githubusercontent.com/assets/958670/21571320/09c31ea6-cec6-11e6-9d7b-d18654a4bf61.png)

**Comment by loganmc10** [comment]
Do you have any non- core options set? Do you have received aspect ratio in the core options set to 4:3 or 16:9?

**Comment by Enverex** [comment]
Only non-defaults are the resolution is increased (to 1280x9xx and 1280x720) and the aspect is set to 16:9.

**Comment by loganmc10** [comment]
So this looks like it is an issue with GLideN64, I've filed a report there:

https://github.com/gonetz/GLideN64/issues/1315

Basically Worms Armageddon doesn't work in widescreen mode for now.

As far as it being slow during the fade, again, that is likely an issue with GLideN64, there are plenty of performance optimisations that could be made there, if only someone had the time.

I'll close this now, you can file a report with GLideN64 about the slowdown if you'd like, but like I mentioned, there aren't really many people that are spending time on that sort of thing, so it will probably just sit there

**Comment by Enverex** [comment]
Fair enough. When is it worth logging an issue here vs there?

**Comment by loganmc10** [comment]
If you are sure it's an issue with GLideN64 (ie. it happens with regular mupen64plus + GLideN64) then it should be filed there. I don't mind testing/verifying it and then filing it there though.

By the way, I just played through a few rounds of Worms on my Shield Tablet and it runs very smooth, including the fade transition before/after the game, so it may just be the case of needing a more powerful GPU. Not saying that nothing could be done to optimise/improve the graphics code, but it does seem to run well on a more powerful device.

**Comment by Enverex** [comment]
Interesting. The device in question has a Mali T628 MP6 which should be relatively capable but obviously isn't anything amazing as far as GPUs go.
