### ISSUE TITLE
Cheats not working on RetroPie

### ISSUE THREAD

**Issue by uniQ168** [GLupeN64/GLupeN64#148]
Hi,

I just updated to the newest commit 510c673 on RetroPie to use it with RetroArch.
I was hoping to get cheats to work, created a .cht with the codes from mupencheat.txt but it's not working. Even tried some other Gameshark codes, but these weren't working either. Am I doing something wrong?

Thanks in advance

**Comment by loganmc10** [comment]
I'll look into this, but I've never actually used cheats before. @ilag11111 may be able to help?

**Comment by uniQ168** [comment]
Thanks! :)

If you need additional information, let me know.

**Comment by loganmc10** [comment]
I just tried 2 cheats with GoldenEye and they both worked, my .cht file looks like this:

```
cheats = 2

cheat0_desc = "Enable All Levels & In-Built Cheat Menu"
cheat0_code = "8006992E FFFF;80069930 FFFF;80069967 FFFF;8006996C FFFF;80069971 FFFF;80069976 FFFF;8006997B FFFF;8006992F FFFF;80069965 FFFF;8006996A FFFF;8006996F FFFF;80069974 FFFF;80069979 FFFF"
cheat0_enable = false 

cheat1_desc = "Infinite Ammo"
cheat1_code = "80079E3B 0001"
cheat1_enable = false
```

**Comment by loganmc10** [comment]
As a side note, it would be awesome if someone could convert the mupencheat.txt file into a RetroArch .cht file and add it to https://github.com/libretro/libretro-database/tree/master/cht

**Comment by uniQ168** [comment]
Well, now I feel stupid, because I was under the impression that codes are separated with a + rather than ;
I will give it another shot and report back if it worked. :D

**Comment by loganmc10** [comment]
The ;'s are line separators, for multi-line cheats, I'm not sure if a + would work or not, any non-hexadecimal character should work, but I could be wrong about that.

**Comment by loganmc10** [comment]
The "all levels" cheat creates a new profile for you:

![untitled](https://cloud.githubusercontent.com/assets/848146/21652103/8cc33af2-d268-11e6-9668-d29e8738e057.png)

Have you tried the infinite ammo cheat? It should work in the Dam level.

**Comment by uniQ168** [comment]
Neither the profile nor the unlimited ammo on dam level works.

I am using a RetroPie 4.1 installation with lr-glupen64 on RetroArch 1.3.6 if that helps. :/

**Comment by loganmc10** [comment]
I tested with RetroArch 1.3.6 and a nightly (this is on Linux), and I've had no issues, so it's hard for me to say what might be wrong, you are clicking "Apply Cheat Changes" after making your choices, correct?

As a side note, this is on a Raspberry Pi I presume? How do you find the performance of lr-glupen64 compared to mupen64plus+GLideN64? I've heard from a few people that it doesn't perform as well, but I'm not sure why that would be.

**Comment by uniQ168** [comment]
Yup, I always hit apply cheats before going back into the game and it's on Raspberry Pi 3. It's still updating, so no new info on that. ;)

I previously ran N64 emulation with mupen64plus+GLideN64 and the performance was nowhere near lr-GLupeN64. Tested it on Super Mario 64 and GoldenEye. Mario 64 was unplayable on mupen64plus+GLideN64, while lr-GLupeN64 runs way smoother. :)

**Comment by uniQ168** [comment]
Updated all packages in RetroPie and it's still not working. :(

**Comment by dankcushions** [comment]
try updating lr-glupen64 by source in retropie. the binaries may not have the cheat changes (i think they were only in the last week or so)

**Comment by loganmc10** [comment]
I can see from the screenshot that the version is the latest, @dankcushions are you able to get it to work?

**Comment by uniQ168** [comment]
@dankcushions I'm already on the latest version.
@loganmc10 Also tried to use other rom dumps of GoldenEye but no luck either. :/

**Comment by loganmc10** [comment]
huh, I have the same problem, it works for me on Linux but not Windows, same ROM

**Comment by uniQ168** [comment]
Tried it myself and it works flawlessly on Linux but on Windows and RetroPie it doesn't.

**Comment by ilag11111** [comment]
I'll look into fixing the Windows build tonight.  No idea what's wrong on the rPi build, and I don't have an rPi to test with.  I do however have an android phone, but no time to install retroarch and test myself until then.  Can one of you check android and see if it's broken there as well?

**Comment by loganmc10** [comment]
I just tested on my Shield Tablet and it doesn't appear to work there either

**Comment by loganmc10** [comment]
By the way @ilag11111 I've updated the buildbot to work with PR's, so if you create a PR, Travis CI will build it and upload it here: http://loganbuildbot.s3-website-us-east-1.amazonaws.com/ (there will be a folder with the number of the PR)

It will update it if you push more things to the PR, so you can just go there for a binary build, since building for Android and Windows can sometimes be a pain.

**Comment by ilag11111** [comment]
Thank you!  You just saved me the major headache of setting up MXE and I don't know what else on my computers.  Now if I can just deal with the major headaches in my life I can actually find time to code.

Another thing to test: the Mupen64Plus core uses the exact same cheat support code line-per-line as this one.  If someone can do a quick test on that, it will narrow down if it's a problem in my code, or elsewhere.

**Comment by uniQ168** [comment]
Sadly, I have no idea howe to use the cheats on mupen64plus. That's why I used GLupeN64 in the first place. ;D

**Comment by loganmc10** [comment]
If someone with a Raspberry Pi wants to help out, I made a "cheatSupport" branch:

https://github.com/GLupeN64/GLupeN64/tree/cheatSupport

With some debugging that ilag11111 needs.

If you could run that build and post the command line output, as seen here:
https://github.com/GLupeN64/GLupeN64/pull/153#issue-199396097

**Comment by loganmc10** [comment]
OK this should be fixed in the latest master (8704447fa7b73fab90888f41c6e06c554ed1cca4), if someone with a Raspberry Pi/RetroPie could test this that would be great.

**Comment by uniQ168** [comment]
Great news! I'll check the new commit after work tomorrow. :)

**Comment by loganmc10** [comment]
I just tested this on Android and it works now so I suspect we'll have good news on the Raspberry Pi as well

Thanks @ilag11111 for looking into this and fixing it!

**Comment by uniQ168** [comment]
Testing new build now.
