### ISSUE TITLE
Direct Controller Access

### ISSUE THREAD

**Issue by tony971** [GLupeN64/GLupeN64#151]
Raphnet has [a plugin](https://github.com/raphnet/mupen64plus-input-raphnetraw) that allows games to directly communicate with original N64 peripherals, given users have his controller adapter. This allows for zero configuration setups of virtually any original hardware. Any chance of integration here?

**Comment by loganmc10** [comment]
This is essentially a no, I only plan on supporting input from libretro/RetroArch, so unless someone else is willing to look into this it won't get done

**Comment by loganmc10** [comment]
I'm going to close this, essentially this would violate the libretro API, all the input should come from libretro, so there is the possibility I would suppose for this to be added as an input driver for RetroArch, but it shouldn't be something implemented by the core.
