### ISSUE TITLE
Savestates failing to save (or possibly failing to load)

### ISSUE THREAD

**Issue by GreenTeaBD** [GLupeN64/GLupeN64#152]
Title says it all for the most part. Either saving states, loading states, or both (it's hard to tell which part is the problem) are broken for me.

I'm using the December 29th x86-64 Windows (I'm on Windows 10) nightly of Retroarch, and have updated GLupeN64.

I have savestates set to save to slot #0 and to save in the content directory. Savestates work fine in every other emulator, I just tested some snes and nes games to make sure, and my n64 roms are not in a write protected area (same place as everything else.) But hitting save state (either in the retroarch menu or using a hot key) GLupeN64 will tell me it successfully saved state #0. If I press load state (same, either in menu or with a hotkey) the game will stutter as if it's loading a state, and then it will say it succeeded in the lower left corner but the game will continue on as normal (not from the savestate, from the point the game was at when the load state button was pressed.)

It saves the sram just fine. And also, every time I make a savestate I do end up with a game.state file in the proper folder (same folder as the srm file, so further evidence it has nothing to do with write permissions or anything).

I've tried saving and then trying to load the state shortly after. Saving, closing the game reloading the game and trying to load the state. Saving, closing retroarch, restarting retroarch, reloading the game and attempting to load the state, and probably some other paths from "save" to "load" but the result is always the same; "100% Loaded State from Slot #0" message, but then the game continues as if I had not tried to load anything.

So I turned on terminal logging and went through the process again with both Mario 64 and Zelda OoT. 
The terminal showed what I suspect are several errors, and a couple that are obviously errors.

Here are the relevant [logs in a pastebin](http://pastebin.com/rsCimkVa)
There are some unexpected (at least by me) differences between the logs for Mario 64 and Zelda OoT. I don't know if that's a part of the issue or not. My guess is that properly saving and loading savestates would not show "Could not read header from state file C:\Emulators\Retroarch\system/GLupeN64/savestate.temp". in the logs. 

Disregarding the weird /\s, \system\GLupeN64\savestate.temp is a real file. It also made .templp, .tempp, .temppr and .tempip files at different times. I've tried deleting them and trying it again, hoping a "corrupt header" causing me problems would go away but that doesn't change anything, it just rebuilds the temp files and the same thing happens.

And that's about the extent of my troubleshooting and debugging ability when it comes to this. I don't know if this is just happening on my computer for some reason or not, but it seems like if it was a universal problem with the build I wouldn't be the first to post about it. So, just let me know if you need anything from me to reproduce this/get logs/whatever else.

**Comment by GreenTeaBD** [comment]
Okay, right after writing this I had an idea for one more thing I could try. I could compile GLupeN64 myself and try dropping in the new dll (the plan was to originally keep my settings and overrides for GLupeN64 and just replace the dll, then if that didn't work to replace everything related to the core. But I didn't have to do the second step.)

Just for the sake of completeness I'll spell out exactly what I did to compile it, even though it's probably all unnecessary. In Windows 10, using the x64 I essentially followed the setup in [this guide](this guide) to get an environment to compile in. Cloned the git and compiled with "make.exe -f Makefile platform=win CC="gcc" CXX="g++" -j6 WITH_DYNAREC=x86_64"

Then just took the dll, backed up the old one, popped it in, loaded up Mari064, made a savestate on the title screen, waited a bit, loaded anddddd... it worked.

Still doesn't explain why it was broken in the first place, or if it's an issue with the binary of GLupeN64, or if it's not reproduceable by anyone else than if it even matters. I don't know.

Still, if you need anything from me just let me know. :)

**Comment by loganmc10** [comment]
I believe I made a change on Jan 3 that might have broken it (https://github.com/GLupeN64/GLupeN64/commit/510c673f3d30f4638be86276a1b3fd21978443bb), I reverted that commit today after seeing your Reddit post, so that probably fixed it

**Comment by loganmc10** [comment]
By the way, there is typically no need to compile it yourself (unless you want to test some old version) you can always find the latest version here: http://loganbuildbot.s3-website-us-east-1.amazonaws.com/

**Comment by GreenTeaBD** [comment]
Alright, great! Well, I hope I helped. And I'm glad you were able to fix it so quickly. Thanks a lot.
