### ISSUE TITLE
(Regrssion) Winback - Screen flashes when firing weapons.

### ISSUE THREAD

**Issue by orbea** [GLupeN64/GLupeN64#154]
OS: `Slackware64-current`
`RetroArch-2017.01.09_338980ef2_master-x86_64-1_git`
`GLupeN64-2017.01.06_08c2b22_master-x86_64-1_git`

In the game winback, almost every time the player character fires his gun the screen will flicker. I traced the issue back to the following commit. This issue does not happen in upstream GLideN64.

This can be easily reproduced at the start of the game during the first confrontation.

Apitrace - http://ks392457.kimsufi.com/orbea/stuff/trace/libretro/glupen64-winback.trace.xz
Apitrace log - http://pastebin.com/AME9mMSV

```
d0859c4c5ca5b248632a510c37eeec2ae743e223 is the first bad commit
commit d0859c4c5ca5b248632a510c37eeec2ae743e223
Author: Logan McNaughton <logan@bacoosta.com>
Date:   Fri Dec 23 14:32:01 2016 -0700

    Change default buffer swap mode

:040000 040000 2b83c89671478d397635fdfedc947b31846dc9c7 0da6eb15480b5ee2629b0f47751c658a0749a963 M	custom
```
d0859c4c5ca5b248632a510c37eeec2ae743e223

**Comment by loganmc10** [comment]
Can you test upstream GLideN63 with bufferswapmode=2 in the mupen64plus.cfg?

The cfg should be in ~/.config/mupen64plus

There is a setting in there called something like "bufferswapmode", set that to 2, I just want to make sure it's not something broken with my implementation. If it is the buffer swap mode, I will add an item to the ini to force winback to use the default buffer swap mode

**Comment by orbea** [comment]
Yea, I can reproduce it in GLideN64 with BufferSwapMode set to 2 instead of 0. Interestingly it happens a lot easier in GLupeN64 than it does upstream. Also it seems upstream has some minor bugs GLupeN64 does not with Winback...

**Comment by loganmc10** [comment]
OK well I'll fix this tomorrow with a change to the ini file, it would probably still be worth it filing an issue with GLideN64. Buffer swap mode = 2 is the default for mupen64plus-ae as well and @fruzita has fixed other issues with this buffer swap mode I believe

**Comment by fzurita** [comment]
Hmm, interesting. I'll check this out when I have time.

**Comment by orbea** [comment]
Right, I will file an issue or more for the things I am noticing upstream probably tomorrow. I will close this issue when the ini has been changed.

**Comment by loganmc10** [comment]
Ok should be fixed by 799d3620d173316eb2ce3749e8818ef473d7b445 if you could confirm

**Comment by orbea** [comment]
This has been resolved, thanks!

**Comment by baptiste0602** [comment]
@loganmc10 : do you force "bufferSwap = 2" for performance ? because, as it's describe in GlideN64 GUI (Zilmar specs plugin) it's the less accurate mode
I don't remember which game but I experience another issues with non-0 modes

**Comment by loganmc10** [comment]
Yes it is for performance, there is a very noticeable difference on my Shield Tablet between the 2 modes.

If there are issues they are quite easy to notice (like this one), so I'd rather have 2 as the default and set it to 0 for the few edge cases there might be, rather than default it to 0 and have worse performance.

**Comment by baptiste0602** [comment]
Ok, thanks for information. I'll open a ticket if I find an issue.
