### ISSUE TITLE
[Request] Real 16/9 aspect ratio

### ISSUE THREAD

**Issue by baptiste0602** [GLupeN64/GLupeN64#155]
glupen64-aspect = "16:9" is not a real 16/9 but refers to WidescreenHack
Could you add the real 16/9 AspectRatio ?

I tested real 16/9 myself with replacing "AspectRatio = 3" by "AspectRatio = 2" at https://github.com/GLupeN64/GLupeN64/blob/master/libretro/libretro.c#L685 and it works well.

The goal is to use 16/9 option that offer some games : Goldeneye, Perfect Dark, ...

Thanks in advance

**Comment by loganmc10** [comment]
I had actually forgotten that some N64 allowed widescreen.

66249f7fd6956b0646cce5a80b00ac4e51182ef6

I've renamed the current 16:9 to "16:9 adjusted" and added the "real" 16:9 option

**Comment by baptiste0602** [comment]
That was very fast, thanks :)
