### ISSUE TITLE
GLideN64.custom.ini gets ignored

### ISSUE THREAD

**Issue by Tasosgemah** [GLupeN64/GLupeN64#158]
When Glupen is run for the first time, it generates some files in the System folder of RetroArch.

The shader folder, the plugin ini and the emulator ini. The plugin ini is GLideN64.custom.ini 

In the standalone version of GlideN64, this ini is used to store per-game options. But in the core version, whatever option i add, it gets overwritten with the defaults. I tried to make the ini read-only but again, the core ignores it.

Now the core has it's own options menu and RetroArch allows to save per game anyway. However, many options of the standalone plugin don't exist in the core version or are simplified. The crop option for instance only allows for "off" or "auto". In the standalone GlideN64 plugin you also have the option to use values manually. These values are normally stored in the GLideN64.custom.ini. But because Glupen ignores this, these values cannot be used.

For instance, i want to use these crop values for WaveRace:

[WAVE RACE 64]
video\cropMode=2
video\cropWidth=8
video\cropHeight=8

But Glupen ignores these settings. Is there any way to fix this?

EDIT: Same thing happens with the Mupen64plus.ini in the folder. I can't use the CountPerOp= option because of this. And the core options lack this feature (Mupen64plus core has the "framerate" option which is the same thing).

**Comment by loganmc10** [comment]
Those ini files are overwritten every time and aren't meant to be modified.

If it didn't overwrite them then people wouldn't get updates when I need to update it (for instance I recently pushed changes to that file to fix graphics in Pokemon Stadium 2 and a few others).

I'm open to suggestions. I'm not really a fan of having options for things like CountPerOp, why would a user need to change that?

For things like custom crop modes I'm torn. RetroArch doesn't have a great system for core options, and I don't want to have an endless list of options without any description of what they do.

I could have the current stuff in GLideN64.custom.ini "built in" and sort of hidden from the user, and use the GLideN64.custom.ini on the filesystem for user defined settings

**Comment by Tasosgemah** [comment]
I don't think the average user will ever going to touch these inis. They are hidden deep inside the system folder of RA anyway... This is more like something that an advanced user would do. I don't see why an advanced user shouldn't have the freedom to change some options if he wants to.

The CountPerOp option is very useful in some games like Goldeneye, Perfect Dark, Starfox, Diddy Kong Racing and other games with unlocked frame rate. You can make them run smoother by changing the value to "1". This is the same thing as the "framerate" option in Mupen64plus core.

Custom crop settings are also better than "auto" since the later may crop more than it should or mess with the aspect ratio (like in Waverace). I already have some games set up on the standalone version and i wanted to use them on the core.

So maybe, if you don't want the main ini to be changed by the user, there could be a second ini that overrides these settings. But overall, i think that protecting the ini from the user somewhat beats it's purpose. In the standalone, its the only way to save settings per game, that's how it should be used IMO.

**Comment by Tasosgemah** [comment]
The last part of your post, i didn't get it, maybe it's the same i suggested in the last part of my post?

**Comment by loganmc10** [comment]
Yes we were saying the same thing.

> The CountPerOp option is very useful in some games like Goldeneye, Perfect Dark, Starfox, Diddy Kong Racing and other games with unlocked frame rate. You can make them run smoother by changing the value to "1". This is similar to the "framerate" option in Mupen64plus core or the "counter factor" settings in PJ64. Glupen is the only solution that doesn't have this option atm. Or maybe i'm wrong and this option is something different?

The mupen64plus libretro core frame rate option and the PJ64 "counter factor" option are different things but may achieve the same result. I suppose I could add that option but I really don't like it, even advanced users won't really know what they're doing besides picking random values, if "1" is really a better value for those games then someone should submit a pull request to mupen64plus-core

**Comment by loganmc10** [comment]
Also 

> But overall, i think protecting the ini from the user somewhat beats it's purpose

I'm not concerned about protecting the ini, it's just that I need a way to update the ini when I need to, but I'll make the default ini settings built in and allow users to add their own settings, I'll work on that tomorrow

**Comment by Tasosgemah** [comment]
Yeah that sounds good. Thanks.

About the CountPerOp, some games work better with 1, other games work better with 3 (2 is usually the default). It may also mess with timings in some games if the wrong value is used. Some racing games may run at a faster speed than normal for instance, instead of just a higher frame rate.

This option is mostly used for testing if a game runs better with "1". The games i mentioned do run better but i think in Mupen it makes Perfect Dark crash (CF1 works fine in PJ64 though).

**Comment by loganmc10** [comment]
Ok you can try the latest build, you can wipe out the GLideN64.custom.ini that is there now, those default settings are now loaded "behind the scenes". New users won't have a GLideN64.custom.ini created by default anymore.

So your GLideN64.custom.ini can just have your settings, for instance your file can just look like this:

```
[WAVE RACE 64]
video\cropMode=2
video\cropWidth=8
video\cropHeight=8
```

**Comment by loganmc10** [comment]
I've also added a "CountPerOp" setting to the core options. Although like I mentioned, if there really is an all around better option for a game there, it should probably be submitted to mupen64plus-core

**Comment by Tasosgemah** [comment]
Thanks for the update :)

The CountPerOp option works like a charm. I tested Perfect Dark with value "1" and it's much smoother than the original.

I can't seem to make the GLideN64.custom.ini work though. All the settings i enter in there get ignored.

Should i move the file somewhere else or rename it?

**Comment by loganmc10** [comment]
No the filename should stay the same, can you post the contents of the file here? It won't recognize every setting, they need to be setup somehwat manually in the code (https://github.com/GLupeN64/GLupeN64/blob/master/custom/GLideN64/mupenplus/Config_mupenplus.cpp#L64-L91), I got lazy and didn't list every possible setting there, but most should be there, if you see one that is missing that you think would be needed I can add it

**Comment by Tasosgemah** [comment]
These are the settings i want to apply

[WAVE RACE 64]
video\cropMode=2
video\cropWidth=8
video\cropHeight=8

[PILOT WINGS64]
video\cropMode=2
video\cropWidth=8
video\cropHeight=8

[STARFOX64]
video\cropMode=2
video\cropWidth=8
video\cropHeight=8

[WORLD DRIVER CHAMP]
video\cropMode=2
video\cropWidth=8
video\cropHeight=8

[BEETLE ADVENTURE RAC]
video\cropMode=2
video\cropWidth=8
video\cropHeight=8

[THE LEGEND OF ZELDA]
video\cropMode=2
video\cropWidth=4
video\cropHeight=4

[MISCHIEF MAKERS]
generalEmulation\enableNativeResTexrects=0
video\cropMode=2
video\cropWidth=12
video\cropHeight=12

**Comment by Tasosgemah** [comment]
Can i ask, the option in the mupen64plus.ini are also included "behind the scenes"?

Because Beetle Adventure Racing should be CountPerOp=3 (like it was in the ini) but it gets overwritten by what i chose in the options. Not a big deal, i can still put 3 and save the setting as an override for this game.

**Comment by loganmc10** [comment]
Nothing changed with mupen64plus.ini, it still gets overwritten each time and shouldn't be modified.

The CountPerOp core option takes precedence over the ini file, this allows you to test different values if you'd like, "0" means take the ini setting (or 2 if there is none, which is the default)

**Comment by Tasosgemah** [comment]
Ah ok.

Something is wrong with Beetle Adventure Racing though, the menu transitions are gone and i thought it was this option's fault but turns out it's something else.

**Comment by loganmc10** [comment]
Can you try the latest build from http://loganbuildbot.s3-website-us-east-1.amazonaws.com/

I think the issue with your ini file is that it was looking for "%20" instead of spaces, anyway I modified the code so that either will work. I also fixed the Beetle Adventure Racing menu transitions

**Comment by Tasosgemah** [comment]
Everything works perfectly now :)

**Comment by loganmc10** [comment]
awesome thanks for helping me test this
