### ISSUE TITLE
Raspberry Pi OpenGL

### ISSUE THREAD

**Issue by Anuskuss** [GLupeN64/GLupeN64#161]
Hey @loganmc10 ,
I apologize in advance for misusing your issue tracker but I have a few questions and this might help other people who are looking for this:

### Backstory
I'm currently using a **Raspberry Pi 2** with vanilla **Raspbian**. I have successfully build `glupen64_libretro.so` with
```Shell
git clone --depth=1 https://github.com/loganmc10/GLupeN64.git
cd GLupeN64/
platform=rpi2 make -j4
```

- If I use the latest **Raspbian**, the project will be compiled with **OpenGL ES** as video driver, correct?
- If I enable the **experimental OpenGL driver**, will the project then automatically be compiled with **OpenGL** support?
- I'm not sure on this one but it seems like the OpenGL driver is somehow integrated in the **kernel**? I've read the [announcing article](https://www.raspberrypi.org/blog/another-new-raspbian-release/) and tested `glxgears` and the article states that it shows wrong colors without the driver, but for me it was running just fine.
- Do I also have to compile **RetroArch** with **OpenGL** support to use **GlupeN64** with OpenGL and if so, do you mind sharing the configuration to do so (I guess it's `./configure --enable-opengl` instead of `--enable-opengles`)?
- Is the **OpenGL driver** enabled even if I comment out `dtoverlay-kms-v3d` (my assumtion is that this only enables the driver for the **Desktop**, but it should always be working)?
- Will the **OpenGL driver** even provide some speedup compared to **OpenGL ES** or shouldn't I even bother doing all these things?
- Is the **Framebuffer Emulation** still heavy on the Raspberry Pi and should I turn it off?
- When I compiled GLupeN64, I didn't get a nice **version number** but only the **git hash**. Do you plan to use some version numbers (like 2.0-hash)?

You are free to only answer some or even none of the questions above. I'm not very familiar with Linux and read so much that my brain is hurting. I hope you can help me with my questions since you seem like a genuine and intelligent guy and you also own a Raspberry Pi so you might be able to help me.

Cheers

**Comment by loganmc10** [comment]
> If I use the latest Raspbian, the project will be compiled with OpenGL ES as video driver, correct?

Both drivers support OpenGL ES. It would be more accurate to describe them as the **closed source** and **open source** driver. By default Raspbian uses the closed source driver, and by default the project is compiled for the closed source driver. (A lot of people online refer to the open source driver as the "OpenGL Driver", but I don't think that is a very good way to describe it)

> If I enable the experimental OpenGL driver, will the project then automatically be compiled with OpenGL support?

No, in order to compile the project for the experimental/open source driver, you need to compile it using ```platform=rpi2-mesa``` or ```platform=rpi3-mesa```.

> I'm not sure on this one but it seems like the OpenGL driver is somehow integrated in the kernel?

This would be a better question for the Raspberry Pi forums, but yes, the new driver is integrated into the kernel. On the user space/software side it uses Mesa.

> Do I also have to compile RetroArch with OpenGL support to use GlupeN64 with OpenGL and if so, do you mind sharing the configuration to do so (I guess it's ./configure --enable-opengl instead of --enable-opengles)?

You need to compile RetroArch to support the new driver, not OpenGL, so you still would compile with --enable-opengles, not --enable-opengl. I believe RetroArch automatically detects the presence of the closed source driver by looking for the ```/opt/vc``` folder. You can probably get it to compile for the new driver by moving that folder, something like ```mv /opt/vc /opt/vc2```

> Is the OpenGL driver enabled even if I comment out dtoverlay-kms-v3d (my assumtion is that this only enables the driver for the Desktop, but it should always be working)?

Again, probably a better question for the Raspberry Pi forums, but no, the new driver will not be enabled unless you have that line in /boot/config.txt. You should be able to compile it either way, but no program will be able to use the new driver without that line.

> Will the OpenGL driver even provide some speedup compared to OpenGL ES or shouldn't I even bother doing all these things?

I tested it around July of 2016 and the new/open source driver was actually significantly slower than the current driver. A lot of work is going into the new driver however, so I wouldn't be surprised if it was faster by now. I wouldn't assume you are going to get much of a performance boost though.

> Is the Framebuffer Emulation still heavy on the Raspberry Pi and should I turn it off?

Framebuffer Emulation increases the load on any GPU, so you will experience a performance improvement if you turn it off. It's actually disabled for the closed source driver since it's very buggy on the Raspberry Pi. This is one area where the open source/new driver is actually better, since it doesn't suffer from the same bugs and framebuffer emulation should work quite well with it.

> When I compiled GLupeN64, I didn't get a nice version number but only the git hash. Do you plan to use some version numbers (like 2.0-hash)?

Like every libretro core, there are no real "versions". I don't know of any libretro core that actually releases a new "version" every now and then, so the git hash is the most accurate way to describe what the user is using.


Hopefully that helps. To offer a bit more of an explanation: OpenGL comes in 2 flavors, OpenGL, and OpenGL ES (OpenGL for phones basically). The closed source driver supports OpenGL ES 2. The open source driver supports OpenGL ES 2 and OpenGL 2 (which is why it sometimes gets called the "OpenGL driver"). GLideN64, the graphics plugin this uses, supports OpenGL ES2&3, and OpenGL 3.3+. So the fact that the new driver supports OpenGL 2 is kind of "useless" to us, and the highest GL version that can be uses is still OpenGL ES 2 for both drivers.

**Comment by Anuskuss** [comment]
@loganmc10 No way you actually took the time to respond to all my questions. Big thank you and my utter respect for clearing everything up :+1:

To sum that up, there're **two drivers**, with the experimental one supporting **OpenGL 2**. Since the new one also has **OpenGL ES** support it should atleast work. I have my hopes up that it will provide a (little) performance boost nevertheless, since it is **GPU accelerated**.
Sorry again if I should rather ask this in the **Raspberry Pi forums** but you're too good at explaining these things that I *have* to ask.

- If I enable the **new driver** (with `dtoverlay-kms-v3d`) does it mean that the closed-sources driver gets disabled? How can I be 100% sure that my build doesn't use the old driver?

- With a fresh copy of Raspbian PIXEL (`4.4.34-v7+`) installed (only installed `mesa-utils`) I get
```
glxinfo | grep OpenGL
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.7, 128 bits)
OpenGL version string: 3.0 Mesa 11.1.0
OpenGL shading language version string: 1.30
```
and `glxgears` shows wrong colors and runs poorly (as expected).

Then I run
```Shell
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install xcompmgr
```
and get the following message from `dist-upgrade`
```
The following NEW packages will be installed:
  libinput-bin libinput10 libllvm3.9 libqt5concurrent5 libqt5core5a
  libqt5dbus5 libqt5gui5 libqt5network5 libqt5opengl5 libqt5printsupport5
  libqt5svg5 libqt5widgets5 libwacom-bin libwacom-common libwacom2
  libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0
  libxcb-render-util0 libxcb-xkb1 libxkbcommon-x11-0 qttranslations5-l10n
  xserver-xorg-input-libinput
The following packages will be upgraded:
  apt apt-utils bash bind9-host ca-certificates dbus dbus-x11 file
  gstreamer1.0-plugins-good libapt-inst1.5 libapt-pkg4.12 libasound2
  libasound2-data libbind9-90 libc-bin libc-dev-bin libc6 libc6-dbg libc6-dev
  libcairo-gobject2 libcairo2 libdbus-1-3 libdns-export100 libdns100
  libdrm-amdgpu1 libdrm-freedreno1 libdrm-nouveau2 libdrm-radeon1 libdrm2
  libegl1-mesa libfcgi-perl libgbm1 libgd3 libgl1-mesa-dri libgl1-mesa-glx
  libglapi-mesa libgles1-mesa libgles2-mesa libgme0 libgnutls-deb0-28
  libgnutls-openssl27 libgudev-1.0-0 libhogweed2 libicu52 libirs-export91
  libisc-export95 libisc95 libisccc90 libisccfg-export90 libisccfg90
  liblwres90 libmagic1 libmpg123-0 libnettle4 libobrender29 libobt2
  libpam-modules libpam-modules-bin libpam-runtime libpam-systemd libpam0g
  libpcsclite1 libpng12-0 libpng12-dev libraspberrypi-bin libraspberrypi-dev
  libraspberrypi-doc libraspberrypi0 libsmbclient libsystemd0 libtevent0
  libtiff5 libudev1 libva1 libwayland-client0 libwayland-cursor0
  libwayland-egl1-mesa libwayland-server0 libwbclient0 libxfont1 libxml2
  locales multiarch-support nodered openbox pcmanfm pi-bluetooth pipanel
  pprompt python-picraft python-werkzeug python3-picraft python3-werkzeug
  raspberrypi-bootloader raspberrypi-kernel raspberrypi-sys-mods
  raspberrypi-ui-mods raspi-config raspi-gpio rc-gui rpi-chromium-mods
  samba-common samba-libs sed sonic-pi systemd systemd-sysv tzdata udev
  va-driver-all wireless-regdb x11-common xserver-common xserver-xorg
  xserver-xorg-core xserver-xorg-input-all xserver-xorg-input-evdev
  xserver-xorg-input-synaptics xserver-xorg-video-fbdev
  xserver-xorg-video-fbturbo
```
which installs a bunch of `libgl*` packages and updates `raspberrypi-kernel` to `1.20161215-1`.

After restarting the Pi (now at `4.4.38-v7+`), without even enabling the driver in `raspi-config`, I get
```
glxinfo | grep OpenGL
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.9, 128 bits)
OpenGL core profile version string: 3.3 (Core profile) Mesa 13.0.0
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.0 Mesa 13.0.0
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 13.0.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```
and `glxgears` shows correct colors and runs at ~72 FPS.

- How is it possible that I didn't "enable" the driver (with writing `dtoverlay-kms-v3d` in `config.txt`) and I still get these results?
- Why does `OpenGL version string` says that the version is `3.0`? I thought the default driver doesn't have OpenGL support?

- Now when I enable the driver in `raspi-config` it installs `compton` and `libconfig9`. `glxinfo` now outputs
```
glxinfo | grep OpenGL
libGL error: MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
OpenGL vendor string: Broadcom
OpenGL renderer string: Gallium 0.4 on VC4 V3D 2.1
OpenGL version string: 2.1 Mesa 13.0.0
OpenGL shading language version string: 1.20
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 13.0.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
```
and `glxgears` still shows the correct colours and runs at ~45 FPS.

With the default `config.txt` (except for `dtoverlay=vc4-kms-v3d` of course) my TV can't display the Pi (*Resolution not supported*). Running `rpi-update`, which updated the kernel to `4.4.44-v7+`, fixed the problem though. Starting `glxgears` again and it runs at ~60 FPS (synchronized with my display).

- So my question is why do I get this results? The open-source driver has `OpenGL 2.1` as you said, but the closed-source one has `3.0`?
- So how can I be sure that I'm even using the right driver when testing if **GLupeN64** (or any other core) gets a performance boost?

- Will I be able to "port" the driver to other systems since right know I'm using **LibreELEC** with **Advanced Launcher**. Or will this be unnecessary since I just need to edit the `config.txt` (because **LibreELEC** uses the latest kernel)?

- [**Dumb question**] Could it be that the driver is somehow compiled into the binary and I just need to compile it on my **Raspbian** with the opensource driver and can just run it fine in another OS?

- And lastly, in addition to the version question, in the **Libretro Info Files** **GLupeN64** has version `2.5`, **GLideN64** had a release with version `2.0`. Why not use `2.0-hash` for example? If you're not interessted in this, I'm sure there is a way for me to change the version to the compile date (`20170125`) to keep track of when I updated it for the last time.

Again, I'm really sorry for the flood of question. Please don't answer any question you feel uncomfortable answering, and I hope you can help me with my curiousity.

Have an nice day sir and thank you for listening.

**Comment by loganmc10** [comment]
> If I enable the new driver (with dtoverlay-kms-v3d) does it mean that the closed-sources driver gets disabled? How can I be 100% sure that my build doesn't use the old driver?

I haven't used my Raspberry Pi in many months, so I'm not 100% sure about everything involed with enabling this new driver. I would use the ```raspi-config``` tool to enable it, it does a few more things than just adding ```dtoverlay-kms-v3d``` to config.txt

> How is it possible that I didn't "enable" the driver (with writing dtoverlay-kms-v3d in config.txt) and I still get these results?

> Why does OpenGL version string says that the version is 3.0? I thought the default driver doesn't have OpenGL support?

The key is to look at the ```OpenGL renderer string``` line. You'll see that without enabling the new driver, the renderer is **llvmpipe**. llvmpipe is what they call a "software renderer". Basically it is OpenGL being done by the CPU instead of the GPU. This was the problem with the current closed source driver, it doesn't work with X windows. So many applications that use OpenGL can't use the closed source driver at all, and they end up using llvmpipe/CPU for OpenGL rendering, which leads to poor performance. llvmpipe happens to support OpenGL 3, but it isn't GPU accelerated at all.

> So how can I be sure that I'm even using the right driver when testing if GLupeN64 (or any other core) gets a performance boost?

I'm not 100% sure on this, but you could try typing ```ldconfig -p | grep GLES```, that should show you were the system is looking for ```libGLESv2.so```. If the location is somewhere inside /opt/vc, that's bad (closed source driver), if the location is somewhere inside /usr/lib, that's good. glxinfo will also tell you, the ```OpenGL renderer string``` says ```Gallium 0.4 on VC4 V3D```, that's good.

> Will I be able to "port" the driver to other systems since right know I'm using LibreELEC with Advanced Launcher. Or will this be unnecessary since I just need to edit the config.txt (because LibreELEC uses the latest kernel)?

I don't know about that, I got the open source driver working on Arch Linux ARM, but every system will be different, you can look at what ```raspi-config``` does when you enable the GL driver by looking here: https://github.com/RPi-Distro/raspi-config/blob/master/raspi-config#L1154-L1247

> [Dumb question] Could it be that the driver is somehow compiled into the binary and I just need to compile it on my Raspbian with the opensource driver and can just run it fine in another OS?

If you compile GLupeN64 on Raspbian for the open source driver, it would run on other Raspberry Pi OSes fine, but that OS would still need to enable the open source driver (by modifying config.txt and having whatever GL packages need to be installed)

> Why not use 2.0-hash for example?

GLupeN64 is a combination of mupen64plus and GLideN64

The 2.5 comes from the fact that the latest release of mupen64plus is version 2.5.

**Comment by Anuskuss** [comment]
Really appreciate your effort to help a noob like me understand this topic, God bless you man.

Some investigation in `raspi-config` revealed that it needs an overlay (`/boot/overlays/vc4-kms-v3d.dtbo`) and the package `libgl1-mesa-dri`. So the driver should work (in theory) when these two things are present.

> [...] but you could try typing `ldconfig -p | grep GLES`, that should show you where the system is looking for `libGLESv2.so`. If the location is somewhere inside /opt/vc, that's bad (closed source driver), if the location is somewhere inside /usr/lib, that's good.
```
ldconfig -p | grep GLES
libbrcmGLESv2.so (libc6,hard-float) => /opt/vc/lib/libbrcmGLESv2.so
libGLESv2.so.2 (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libGLESv2.so.2
libGLESv2.so (libc6,hard-float) => /opt/vc/lib/libGLESv2.so
libGLESv1_CM.so.1 (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libGLESv1_CM.so.1
```

- So `libGLESv2.so` is the close-source driver and `libGLESv2.so.2` is the open-source driver. Should I manually link them or is it already working (I mean I see the effect on `glxgears` and `glxinfo` is also correct)?

> If you compile GLupeN64 on Raspbian for the open source driver, it would run on other Raspberry Pi OSes fine, but that OS would still need to enable the open source driver (by modifying config.txt and having whatever GL packages need to be installed)

- Some my plan is now to do some benchmarking, to get an idea if the open-source driver can perform same or even better than the close-source one. If I comment out `dtoverlay-kms-v3d` and compile **GLupeN64** with `platform=rpi2-mesa` the old driver should be used anyway, correct?

- I'm gonna do some test now and report my results, I hope I understand everything correctly by now. By the way, is there another method of benchmarking than to just look at the RetroArch FPS?

**Comment by loganmc10** [comment]
> So libGLESv2.so is the close-source driver and libGLESv2.so.2 is the open-source driver. Should I manually link them or is it already working (I mean I see the effect on glxgears and glxinfo is also correct)?

I wouldn't mess with how they are all linked together. If you want to be sure you are using the open source driver, you can just move the /opt/vc folder like ```sudo mv /opt/vc /opt/vc2``` or something, that will break the closed source driver, so if things still work, you can be sure you are using the open source driver.

>  If I comment out dtoverlay-kms-v3d and compile GLupeN64 with platform=rpi2-mesa the old driver should be used anyway, correct?

The old/closed source driver is used by compiling GLupeN64 like ```platform=rpi2```, the new/open source driver is used by compiling like ```platform=rpi2-mesa```

> By the way, is there another method of benchmarking than to just look at the RetroArch FPS?

The FPS is probably the best measure of overall performance. You can look at other things like the CPU usage during a game, when I last tested the open source driver around July 2016, it used wayy more CPU time than the closed source driver.

**Comment by dankcushions** [comment]
> I have my hopes up that it will provide a (little) performance boost nevertheless, since it is GPU accelerated.

point of order: GLES and Open GL are both GPU accelerated :)

i don't know why the new driver would be more performant in applications that have open gl 2.0 and GLES 2.0 pathways. i guess maybe if there are functions in the GL subset that aren't in the GLES subset that are otherwise done with slower software equivalents? interested in the results!

**Comment by loganmc10** [comment]
> i don't know why the new driver would be more performant in applications that have open gl 2.0 and GLES 2.0 pathways. i guess maybe if there are functions in the GL subset that aren't in the GLES subset that are otherwise done with slower software equivalents? interested in the results!

Both drivers will use GLES2.0, so there is no difference there. I doubt there will be any performance difference, but there is always the possibility that one driver will do something more efficiently than the other. The new driver works flawlessly with framebuffer emulation, whereas the current closed source driver hardly works at all with it, so if they are on par performance-wise, I would say the new driver wins in that sense.

**Comment by Anuskuss** [comment]
I don't know if I did everything correctly, but here are my results anyway (will update if wrong)

### Default configuration: Ø 22.5 FPS
- Get **Raspbian PIXEL**
- `sudo apt-get update && sudo apt-get upgrade && sudo rpi-update`
- `git clone https://github.com/libretro/RetroArch.git`
- `./configure --disable-kms --enable-opengles --disable-dispmanx --disable-vg --enable-neon --enable-floathard --enable-udev && make`
- `git clone --depth=1 https://github.com/loganmc10/GLupeN64.git`
- `platform=rpi2 make -j4`

### Open Source Driver with OpenGL ES: Ø N/A
- Following [this](https://github.com/anholt/linux/issues/57#issuecomment-244687486)
- `sudo apt-get install libudev-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev`
- `sudo mv /opt/vc /opt/vc2`
- `cd RetroArch`
- `./configure --enable-kms --enable-opengles --disable-dispmanx --disable-vg --enable-neon --enable-floathard --enable-udev && make`
- But it gave me `make: *** No rule to make target '/opt/vc/include/EGL/egl.h', needed by 'obj-unix/gfx/drivers_shader/shader_null.o'.  Stop.`, so I moved `/opt/vc2` back to its place.
- `cd GLupeN64`
- `platform=rpi2-mesa make -j4`
- Unfortunately it gave me `collect2: error: ld returned 1 exit status`. So I checked `ldconfig` and got
```
ldconfig -p | grep GLES
libGLESv2.so.2 (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libGLESv2.so.2
libGLESv2.so (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libGLESv2.so
libGLESv1_CM.so.1 (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libGLESv1_CM.so.1
```
So by installing these packages above, the `ldconfig` got fixed (?) but didn't let me build **GLupeN64**. I'm doing a fresh install right now. In the mean time you can control my steps and tell me what went wrong.

**Comment by loganmc10** [comment]
Unfortunately I don't have a working Raspberry Pi anymore, so I can't really test these things to figure out what might be wrong,

One thing I'll say, you need to make sure you do a ```make clean``` before you do a ```make``` to ensure that you start with a fresh directory.

**Comment by Anuskuss** [comment]
I'm almost at the point where I'm giving up since it is just too much effort. My main reason for doing all of that was to may get a quick minor performance boost from using the open-source driver because I *love* playing **Mario Kart 64** with my friends and my RPi2 can't really do 4-player splitscreen that well, but I'll continue to try some more things and if that doesn't work, well, it doesn't work.

Maybe in the future the driver will always be enabled and all the emulators gonna be using it, but right now it may not be worth it.

So back to the topic. I installed a fresh **Raspbian**, updated everything and then compiled **RetroArch** again (for reference). Then I enabled the driver and recompiled it again (this time with `--disable-kms` because I need to install those packages to use **KMS/EGL**). I compared the md5sums and they were the same. I don't really know what **KMS** is but I think it's necessary because `libGLESv2.so` was linked against the close-source driver (?)

Then I tried to compile **GLupeN64** again (with a fresh install) and got a different error message:
```
./libretro-common/include/glsym/rglgen_headers.h:55:23: fatal error: GLES2/gl2.h: No such file or directory
 #include <GLES2/gl2.h>
                ^
compilation terminated.
In file included from ./libretro-common/include/glsm/glsm.h:30:0, from ./custom/glsm/glsmsym.h:26, from GLideN64/src/OpenGL.h:17, from GLideN64/src/DepthBuffer.cpp:7:
./libretro-common/include/glsym/rglgen_headers.h:55:23: fatal error: GLES2/gl2.h: No such file or directory
Makefile:315: recipe for target 'GLideN64/src/DepthBuffer.o' failed
Makefile:315: recipe for target 'GLideN64/src/Combiner.o' failed
```

If you wanna fix it go ahead - maybe we can figure something out and include it in the **wiki**. If not, and you have all right to to do so, I'll close this issue and I'll try pushing my RPi2 on a different way (maybe mount a fan :grimacing: ). Still wanna say thank you for your support and good luck with your project :+1:

**Comment by loganmc10** [comment]
You're really close to getting this working. That error was my fault, I've pushed a fix to glupen64, hopefully it will work now, so can you do a ```git pull``` or re-clone GLupeN64 and try again?

If you're goal here is increased performance I fear you may be disappointed, you'll probably have better luck looking into GPU overclocking if you haven't already.

**Comment by Anuskuss** [comment]
10 minutes into compiling **mupen64plus** and you post a fix :smile: 
Will try that right now and report my result.

**Comment by loganmc10** [comment]
If you compile RetroArch with ```--enable-opengles``` then it will use OpenGL ES, which is what you want. There is no automatic benefit to using OpenGL over OpenGL ES, it's not like OpenGL is faster or something, they are just different API's, and in the case of RetroArch/GLupeN64, it uses OpenGL ES

**Comment by Anuskuss** [comment]
I was thinking that certain things may get handled better by OpenGL (since I've read that you have to do some tricky things to do OpenGL stuff in OpenGL ES), but anyway, here are my results:

After compiling it, I disabled `vc4-kms-v3d` in `config.txt` to get a comparison. I ran into severe issues (half the screen was white in menu, no underground ingame). I checked the settings and deactivated **Framebuffer Emulation** and this time it worked. Don't quote me on that (because I haven't done a proper test) but it ran worse, something like 18-21 FPS.
Then I reactivated the driver and ran it again. I couldn't get **RetroArch** to start (`* failed to add service - already in use?`) so I checked **Google** and tinkered with my `config.txt` and `cmdline.txt`. Increasing my `gpu_mem` and adjusting my `cma` made my system pretty unstable and `retroarch` still wouldn't launch.

So I installed a fresh copy and did everything again. Again, without the driver enabled, I ran `retroarch` and I got a white screen. The console got spammed with
```
eglCreateImageKHR: failed to create image for buffer (nil) x300c
```
I switched to **RGUI** and that seemed to work. With a working GUI now I started **GLupeN64** and this time, it didn't work at all:
```
context_reset.
plugin_start_gfx success.
open: No such file or directory
glGetError 0x505
```

I don't know what I did differently this time, but I continued with my experiment. I reenabled the driver and ran it again. But unfortuanely I still got
```
* failed to add service - already in use?
```
Increasing the `gpu_mem` didn't solve this.

So I'm (finally) giving up on his. It was a fun experience, and in the future somebody may try this and can provide better results, but I'm just to bad for this stuff.
I don't think we should create a Wiki entry for that (yet) but if you want to, I can write one for you.

Anyway, thank you for supporting me and I hope that in some day in the future, this driver will be default and everything will always run at fullspeed :smile: 

Cheers :v:

**Comment by loganmc10** [comment]
I lost my SD card reader so I can't get my Pi booted right now, if I ever get around to replacing it I'll try this out and post my results here.
