### ISSUE TITLE
Mario Party 3 game board not aligned with background/camera.

### ISSUE THREAD

**Issue by NeoVidia** [GLupeN64/GLupeN64#171]
Hi, first of, thanks for all the hard work you've already put it!

Like the title states, when starting a game of Mario Party 3 the board spaces, characters, etc. except the background re-align to the left mostly outside of camera view. 

Correctly Aligned:
![mario party 3 u f3 -170208-130710](https://cloud.githubusercontent.com/assets/25638114/22738608/648da9da-ee08-11e6-9556-7def828baaff.png)

Seconds later, incorrectly aligned:
![mario party 3 u f3 -170208-130737](https://cloud.githubusercontent.com/assets/25638114/22738613/6f944b86-ee08-11e6-8f8d-2f9691e82a7f.png)

If you let dice head mcgee here explain the game to you, you can see it quickly re-aligning itself. If you just start a normal game the board will start aligned to the left. 

I'm using a RPi 3 Model B with RetroPie 4.1.11 on source build version 7b7cb25.

EDIT: Litteraly went through every config option to see if it would somehow change anything, but nope. It does require Framebuffer Emulation to prevent graphical bugs though.

**Comment by loganmc10** [comment]
You need to play at native resolution (320x240)

**Comment by NeoVidia** [comment]
Right, that works, the one setting I didn't change.
