### ISSUE TITLE
(Android) Ocarina of Time - Missing/flashing textures with GLES3

### ISSUE THREAD

**Issue by orbea** [GLupeN64/GLupeN64#70]
Using the libretro build bot version one of the latest commits probably yesterday caused the game to constantly flash missing textures starting with the nintendo logo with both GLES2 and GLES3. No issues with mupen64plus-ae from the fdroid repo.

GLES3 was doing it before too, but far less frequently. Unfortunately I'm not able to bisect or help debug much on android yet...

**Comment by orbea** [comment]
Turning off framebuffer emulation fixes it for both GLES2 and GLES3.

**Comment by loganmc10** [comment]
Ya it was probably something I broke yesterday. If you have the patience you can update your buildbot URL to pull the latest version from my buildbot (in retroarch.cfg):

core_updater_buildbot_url = http://loganbuildbot.s3-website-us-east-1.amazonaws.com/cores

It's probably working today, it works on my phone at least.

**Comment by orbea** [comment]
I can't change the url apparently. The retroarch keyboard overlay has a broken shift key so no `:`. Do you know about how long it takes for main buildbot to update?

**Comment by loganmc10** [comment]
Ya the RetroArch keyboard thing is strange, I don't know why it can't use the built-in Android keyboard. I edit the file by downloading a text editor app and editing it outside of RetroArch.

I think it just builds once a day, I'm not sure what the schedule is.

**Comment by orbea** [comment]
Okay, a text editor worked. The problem still persists however.

**Comment by loganmc10** [comment]
Can you describe the problem a bit more? Is the whole screen flickering? Are just some textures disappearing? Does it happen at a consistent pace, or is the flickering more random?

**Comment by orbea** [comment]
It happens at a constant rate, large portions of whatever is rendered will flicker between a correct state and a state where nothing is rendered similar to some images in issue https://github.com/loganmc10/GLupeN64/issues/68 or where only part of in game character such as Link will suffer this much like the third image in issue https://github.com/gonetz/GLideN64/issues/1134 except not in the start menu. Some things will render correctly such as the start menu, the interior of Link's house, the sky in the opening animation and the loading loading menu.

**Comment by loganmc10** [comment]
And you said this was recent right? It hasn't always been doing this?

**Comment by orbea** [comment]
It was doing something similar while GLES3 was broken in other ways, but what I suspect was a firmware update fixed it and caused GLES3 to do this sporadically. However after updating both cores yesterday from the libretro buildbot it resumed for both at the same frequency.

**Comment by loganmc10** [comment]
This is especially tricky since I can't reproduce it on my phone. You could try to reset/delete your retroarch-core-options.cfg file to see if there is some setting in there that has been changed is messing it up.

Besides that, you might need to learn how to gather logcat output (adb logcat), there is also an option under "Developer Options" called "Enable OpenGL Traces" that will dump OpenGL errors to the logcat output.

**Comment by orbea** [comment]
That was easy enough, however its a lot of noise and I'm not sure it has anything relevant.

http://ks392457.kimsufi.com/orbea/stuff/logs/libretro/logcat_glupen64_gles2.log

**Comment by loganmc10** [comment]
I think if you choose "call stack on glGetError" under "Enable OpenGL Traces" it will only print the errors (still prints them to the logcat, but just the errors)

**Comment by orbea** [comment]
Unfortunately it seems my developer options does not include that feature.

I have found this site with some ways to filter out the logs, but still I'm not convinced its so helpful.
http://adbshell.com/commands/adb-logcat

The above log was made with `adb logcat *:D`, this is with `adb logcat *:I`. Trying to show warnings and errors becomes increasingly less helpful...
http://pastebin.com/CgtqT24F

**Comment by loganmc10** [comment]
Ya I don't see anything obvious in the logs, I've got a phone at home that actually has the same GPU as you (Adreno 405), so I'll test that tonight.

**Comment by loganmc10** [comment]
I just tested Zelda OoT on a Sony Xperia M4 Aqua, which has an Adreno 405 and Android 6 and I didn't have this issue, it all worked fine except that it runs really slow (GLideN64 doesn't work well on Adreno GPUs).

Are you sure you grabbed the version from my buildbot? I made it use the git revision as the core version number now so you can see what commit you are running

**Comment by orbea** [comment]
Yes, they are the only two cores in your build bot so its hard to confuse it. :) I updated them again and it shows the commit 7244594, of course the issue still persists. If its not the gpu itself its probably the driver. This is an Alcatel Onetouch Idol 3 with what I presume their latest android marshmallow update.

**Comment by loganmc10** [comment]
Android is tricky to test because it has security measures in place around .so files. The .so file must reside "inside" the app, it can't be loaded from external storage like an SD card. So you need to build it and then upload to some kind of http service, and setup a .index_extended file so that it can act like a buildbot, then update your buildbot URL, etc....

If you had a rooted phone you could copy the .so file into the internal app storage. It would be nice if RetroArch had a feature that copied a core from external storage into the app, since only the all itself has permissions to write to that location.

**Comment by orbea** [comment]
I guess I can try building the cores and put them on a server with an .index_extended file to bisect with. I'll see about that probably tomorrow.

Rooting the phone will be hard because they have apparently removed fastboot, so my best option seems to be to restore to the default firmware, root it and then upgrade the firmware again...

**Comment by loganmc10** [comment]
If you go to http://loganbuildbot.s3-website-us-east-1.amazonaws.com/cores in your browser you'll see my .index_extended file, it never changes, even when I update the cores.

I'm almost certain the problem is either rglBindFramebuffer or rglTexParameteri in custom/glsm/glsm.c

You can try changing those functions to look like this:

```
void rglTexParameteri(GLenum target, GLenum pname, GLint param)
{
      glTexParameteri(target, pname, param);
}
```

```
void rglBindFramebuffer(GLenum target, GLuint framebuffer)
{
   if (framebuffer == 0)
      framebuffer = hw_render.get_current_framebuffer();
   glBindFramebuffer(target, framebuffer);
}
```

**Comment by orbea** [comment]
So after a bit of effort I managed to host my own cores for the downloader...

Neither of those changes worked, so I went back to https://github.com/loganmc10/GLupeN64/commit/8c8e23717a6a941cd07bc739d819479059e30786 and found it worked again.

After bisecting this commit was revealed as bad.
```
439c439d7960554c5bbac6038632227b6a66e416 is the first bad commit
commit 439c439d7960554c5bbac6038632227b6a66e416
Author: Logan McNaughton <logan@bacoosta.com>
Date:   Thu Oct 6 12:51:44 2016 -0600

    Some GL performance improvements

:040000 040000 1c8e433d3bb99c2cd4defc8f33dabdec1b00adbc 7221ad329b97d6f460da0b80ec604d61bf9c628d M	custom
```
https://github.com/loganmc10/GLupeN64/commit/439c439d7960554c5bbac6038632227b6a66e416

**Comment by loganmc10** [comment]
I've looked at that commit over and over and I can't see what would be causing the problem. I'd rather not revert the whole thing since it seems like it's not a wide spread issue.

You could try commenting out ```if (gl_state.bindbuffer.buffer[0] != 0)``` in glsm_state_bind so that ```glBindBuffer(GL_ARRAY_BUFFER, gl_state.bindbuffer.buffer[0]);``` is executed every time, but I doubt that would do anything.

The only time I ever experienced flashing textures on Android was an issue with rglBindTexture in custom/glsm/glsm.c, you could try making that function look like this:

```
void rglBindTexture(GLenum target, GLuint texture)
{
   glBindTexture(target, texture);
   gl_state.bind_textures.ids[gl_state.active_texture] = texture;
}
```

If that works that would be a pretty good hint as to what is wrong.

**Comment by loganmc10** [comment]
By the way, does this only happen for the Ocarina of Time? Or does it happen in other games as well?

**Comment by orbea** [comment]
Neither of those work either... I tried playing with just about all the changes in the commit, but changing them individually doesn't make a difference. However reverting the entire commit did work.

It seems to be at least a few games, but I have only tried Ocarina of Time and Super Smash Bros which both do similar. Disabling framebuffer emulation works for both.

**Comment by orbea** [comment]
I got it! There might be a better solution, but changing it back like this solves the issue for both Ocarina of Time and Super Smash Bros.
```
diff -ur GLupeN64/custom/glsm/glsm.c GLupeN64/custom/glsm/glsm.c
--- GLupeN64/custom/glsm/glsm.c	2016-10-08 13:41:25.766541129 -0700
+++ GLupeN64/custom/glsm/glsm.c	2016-10-08 14:06:58.363996761 -0700
@@ -185,7 +185,8 @@
    } readbuffer;
 
    GLuint vao;
-   GLuint framebuf[2];
+   GLuint framebuf;
+   GLenum framebuf_target;
    GLuint program;
    GLenum active_texture;
    int cap_state[SGL_CAP_MAX];
@@ -758,8 +759,8 @@
    int i, p;
    for (i = 0; i < n; ++i) {
       for (p = 0; p < 2; ++p) {
-         if (framebuffers[i] == gl_state.framebuf[p])
-            gl_state.framebuf[p] = 0;
+         if (framebuffers[i] == gl_state.framebuf)
+            gl_state.framebuf = 0;
       }
    }
 }
@@ -1695,13 +1696,17 @@
  */
 void rglBindFramebuffer(GLenum target, GLuint framebuffer)
 {
+   if (!resetting_context) {
+      const GLenum discards[]  = {GL_DEPTH_ATTACHMENT};
+      glDiscardFramebufferEXT(gl_state.framebuf_target, 1, discards);
+   }
    if (framebuffer == 0)
       framebuffer = hw_render.get_current_framebuffer();
    if (target == GL_FRAMEBUFFER) {
-      if (gl_state.framebuf[0] != framebuffer || gl_state.framebuf[1] != framebuffer) {
+      if (gl_state.framebuf != framebuffer || gl_state.framebuf_target != target) {
          glBindFramebuffer(target, framebuffer);
-         gl_state.framebuf[0] = framebuffer;
-         gl_state.framebuf[1] = framebuffer;
+         gl_state.framebuf = framebuffer;
+         gl_state.framebuf_target = target;
       }
    }
 #ifndef HAVE_OPENGLES2
@@ -2052,8 +2057,8 @@
    gl_state.bindbuffer.buffer[0]        = 0;
    gl_state.bindbuffer.buffer[1]        = 0;
    gl_state.bindvertex.array            = 0;
-   gl_state.framebuf[0]                 = hw_render.get_current_framebuffer();
-   gl_state.framebuf[1]                 = hw_render.get_current_framebuffer();
+   gl_state.framebuf                    = hw_render.get_current_framebuffer();
+   gl_state.framebuf_target             = RARCH_GL_FRAMEBUFFER;
    gl_state.cullface.mode               = GL_BACK;
    gl_state.frontface.mode              = GL_CCW;
 
@@ -2113,15 +2118,7 @@
          glEnable(gl_state.cap_translate[i]);
    }
 
-#ifdef HAVE_OPENGLES2
-   glBindFramebuffer(GL_FRAMEBUFFER, gl_state.framebuf[0]);
-#else
-   if (gl_state.framebuf[0] == gl_state.framebuf[1])
-      glBindFramebuffer(GL_FRAMEBUFFER, gl_state.framebuf[0]);
-   else
-      glBindFramebuffer(GL_DRAW_FRAMEBUFFER, gl_state.framebuf[0]);
-      glBindFramebuffer(GL_READ_FRAMEBUFFER, gl_state.framebuf[1]);
-#endif
+   glBindFramebuffer(gl_state.framebuf_target, gl_state.framebuf);
 
    if (gl_state.blendfunc.used)
       glBlendFunc(
```

**Comment by loganmc10** [comment]
This is so interesting, does:
```
if (!resetting_context) {
      const GLenum discards[]  = {GL_DEPTH_ATTACHMENT};
      glDiscardFramebufferEXT(gl_state.framebuf_target, 1, discards);
   }
```

Make any difference if it's gone? They line was causing issues for Windows folks, that's why I removed it

**Comment by orbea** [comment]
Removing this from the patch will break it again.
```
+   if (!resetting_context) {
+      const GLenum discards[]  = {GL_DEPTH_ATTACHMENT};
+      glDiscardFramebufferEXT(gl_state.framebuf_target, 1, discards);
+   }
```
However adding only something like this instead does not fix it, am I doing something wrong?
```
+   if (!resetting_context) {
+     const GLenum discards[]  = {GL_DEPTH_ATTACHMENT};
+    glDiscardFramebufferEXT(gl_state.framebuf[1], 1, discards);
+ }
```

**Comment by loganmc10** [comment]
The first argument of glDiscardFramebufferEXT needs to be the target, so you'll have better luck with something like this:

```
+   if (!resetting_context) {
+     const GLenum discards[]  = {GL_DEPTH_ATTACHMENT};
+    glDiscardFramebufferEXT(GL_FRAMEBUFFER, 1, discards);
+ }
```

That should work on GLES2, GLES3 might need something a little more complex.

The reason this is so interesting is there is a very similar issue that affects the Raspberry Pi. (https://github.com/gonetz/GLideN64/issues/1084) If you look inside GLideN64/src/FrameBuffer.cpp you'll see a few instances of glDiscardFramebufferEXT inside ```#ifdef VC``` (the definition used for the Raspberry Pi).

I thought it would be safe to just do a glDiscardFramebufferEXT each time you bind a new Framebuffer, but that caused issues on Windows for some people (https://github.com/loganmc10/GLupeN64/issues/68)

**Comment by orbea** [comment]
Yea, I see that now and it works, thanks! It still occurs with GLES3 though.

**Comment by loganmc10** [comment]
Can you try this app:

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

And under emulation profiles choose "GLideN64 ES2" or ES3, I'd be really surprised if this only happens with GLupeN64

Also just to confirm, that glDiscardFramebufferEXT stuff is the only thing you need to get it working with GLES2? All the other stuff is OK at is it currently committed?

**Comment by orbea** [comment]
I do not have a google account and would rather not use the google play store. I have it from the fdroid repo, but I'm not sure if that is too old or not? Its version 2.44 and version code 363, is there another place to get it or perhaps even compile it myself? 

I do not know how to turn framebuffer emulation on it (If possible?) and can't test it properly with the fdroid version.

Yes, this is all that is needed for GLES2, GLES3 will need something better though.
```
+   if (!resetting_context) {
+     const GLenum discards[]  = {GL_DEPTH_ATTACHMENT};
+    glDiscardFramebufferEXT(GL_FRAMEBUFFER, 1, discards);
+ }
```

**Comment by loganmc10** [comment]
@fzurita do you have an apk that @orbea can use?

**Comment by loganmc10** [comment]
By the way @orbea there is a core option called "glupen64-PolygonOffsetFactor" (scale used to calculate depth values). You can try the different options for that as well (need to close/reopen after change), they might fix it, but I'm less confident in that

**Comment by loganmc10** [comment]
A value of -0.2f might be correct for your GPU for glupen64-PolygonOffsetFactor

**Comment by fzurita** [comment]
https://drive.google.com/file/d/0B57Ioy26LWegOGFhalBTZ2tiOTQ/view?usp=sharing

That's a link to the latest build in the play store as an apk.

**Comment by fzurita** [comment]
You will have to create a new emulation profile to get access to the GLideN64 settings. Make sure you select that emulation profile before starting a game

**Comment by orbea** [comment]
I tried every value and it made no difference with GLES3.

**Comment by orbea** [comment]
Thanks @fzurita , however that link has the same problem. It requires a google account.

**Comment by fzurita** [comment]
Can you make one with fake information just to get the download?

**Comment by orbea** [comment]
That defeats the point and is a huge hassle, but nvm and thanks.

**Comment by fzurita** [comment]
Ok

**Comment by loganmc10** [comment]
Here is a publicly available link to the file:

https://s3.amazonaws.com/loganfiles/app-release.apk

**Comment by fzurita** [comment]
Hehe is a Microsoft OneDrive download link, no login should be required:

https://1drv.ms/u/s!AvzlIlJVetTQgagdpq48ItiJBmxCYg

**Comment by fzurita** [comment]
Well, now there is 2 more links... Lol

**Comment by orbea** [comment]
Thanks! Yes, it happens with mupen64plus-ae, turning off framebuffer emulation will fix it there.

**Comment by fzurita** [comment]
Sounds like a driver bug.... There are too many of those to count.

**Comment by fzurita** [comment]
Here is the code for it: https://github.com/mupen64plus-ae/mupen64plus-ae?files=1

**Comment by loganmc10** [comment]
https://github.com/mupen64plus-ae/mupen64plus-ae

@fzurita maintains mupen64plus-ae and that "FZ edition" is basically the git version of the repo.

Well I'm glad it's not specific to GLupeN64, it's some kind of strange phantom bug with GLideN64 thst only affects some GPU drivers. I will apply the glDiscardFramebufferEXT (for GLES2 and 3) fix just for GLES devices so it won't break it for the Windows people.

**Comment by orbea** [comment]
Ah, thanks for the links and explanation. I probably could this myself now for future use. Thanks.

**Comment by fzurita** [comment]
Well, technically speaking, the FZ Edition is at this link:
https://github.com/fzurita/mupen64plus-ae/tree/fz-master?files=1

It's identical to the other code but I added an in-app donation button.

**Comment by orbea** [comment]
I think once this is fixed in the GLupeN64 glsm.c I should make an issue report on the upstream GLideN64 repo, maybe gonetz might have more ideas.

**Comment by loganmc10** [comment]
Ya there have been a number of issues that are all basically related to this issue:

https://github.com/gonetz/GLideN64/issues/1084
https://github.com/gonetz/GLideN64/pull/1051
https://github.com/gonetz/GLideN64/pull/1031
https://github.com/gonetz/GLideN64/issues/1011
https://github.com/gonetz/GLideN64/issues/994#issuecomment-222540527

It's some kind of issue with depth clearing but I have no idea what is causing it only on a handful of GPU drivers

**Comment by loganmc10** [comment]
@orbea d5cf7c63d7afefa55432c29a4f2fe278da59f762 should hopefully fix this for GLES2 and GLES3. Please let me know

**Comment by orbea** [comment]
Thanks! It is fixed for GLES2, but unfortunately its still broken with GLES3 and frame buffer emulation.

**Comment by loganmc10** [comment]
Has it ever worked with GLES3 for you? In your first post you said "GLES3 was doing it before too", so are we back to that? Or is it worse than it used to be?

**Comment by orbea** [comment]
No, GLES3 has never worked. It has been better though. Before the firmware update it was broken in very different and much worse ways, then it started doing that infrequently and finally it shows the same issue GLES2 had.

**Comment by loganmc10** [comment]
This is a tricky one, I just committed something that has a very slight change of fixing it, but I doubt it.

The only other shot is you could try disabling the core option ```Enable writing of fragment depth (glupen64-EnableFragmentDepthWrite)```

If that does nothing, then I'm pretty much out of ideas, you might just have the unfortunate circumstance of having a GPU driver that doesn't like GLideN64

**Comment by orbea** [comment]
Unfortunately not for either, thanks for trying.

**Comment by fzurita** [comment]
I really hope they someday Google allows updating GPU drivers like desktop Linux can....

**Comment by loganmc10** [comment]
Since this is also happening with mupen64plus-ae is it fair to say that this is a GLideN64 bug (slash driver bug?) and perhaps an issue can be opened there?

**Comment by orbea** [comment]
In case this is still useful here is the output of `adb shell dumpsys SurfaceFlinger`.

http://pastebin.com/mY2zhCdW

**Comment by orbea** [comment]
I guess this is fixed now with Ocarina of Time and Super Smash Bros, so I will close this.

**Comment by orbea** [comment]
@loganmc10 And this is fixed again in GLES3. I will if I can find a bad commit again later...

**Comment by loganmc10** [comment]
You have one interesting phone lol

**Comment by loganmc10** [comment]
@fzurita We finally tracked this down, it happens for @orbea when ```generalEmulation.enableFragmentDepthWrite = 0```

When fragment depth writing is enabled, no problem, but when it is disabled this happens. It is probably the same problem on the Raspberry Pi since enableFragmentDepthWrite is always set to 0 on GLES2

**Comment by loganmc10** [comment]
Since this problem happens on GLES2 and GLES3, I assume the problem must be in gDP.cpp (gDPFillRectangle), since all the other code that is affected by enableFragmentDepthWrite doesn't get executed for GLES2. It's also worth noting that the gDPFillRectangle code executes clearDepthBuffer, which is where @fzurita put a special #ifdef for Android to fix this problem on PowerVR

**Comment by fzurita** [comment]
Hmm... interesting. I don't have much to add since I haven't seen this problem in my builds. I'm not sure how enableFragmentDepthWrite would fix it, all that's doing is making the GLSL shader code that write to fragDepth to not be executed. Unless that changed since I initially implemented it.

**Comment by loganmc10** [comment]
Well it could be that it was always broken (on some devices) with enableFragmentDepthWrite disabled, its just that having it enabled happens to fix the problem. This has happened on the Raspberry Pi ever since Framebuffer Emulation worked (merged June 26).

So it's probably not a case of enableFragmentDepthWrite=0 breaking it, more like enableFragmentDepthWrite=1 fixes it.

**Comment by fzurita** [comment]
The thing is that it shouldn't fix it. enableFragmentDepthWrite is only needed for a few games. If you look at what it does in GLSL, I don't see how it could fix this problem, unless it's somehow triggering a different path in the driver.

**Comment by loganmc10** [comment]
The other weird thing is that with enableFragmentDepthWrite=0, my little glDiscardFramebuffer trick fixes the problem on GLES2 (on the Raspberry Pi and @orbea's phone), but not on GLES3.

I'll play around a bit on my Raspberry Pi over the next few weeks when I get a chance now that it seems its narrowed down a little bit (maybe?)

**Comment by fzurita** [comment]
Writing to fragDetph is only available in GLES 3.0+, so it may not necessarily work unless there is some kind of extension that allows you to do it?

**Comment by loganmc10** [comment]
Ya its only a GLES3+ thing. The problem is that it's a real punch to the gut for performance (the same reason that glsl discard is bad for performance, it ruins the GPU's ability to optimize), so I'd rather have it off by default (on mobile) since it doesn't seem to affect the compatibility of too many games.

**Comment by orbea** [comment]
I should add that currently these issues are with Super Smash Bros, framebuffer emulation and GLES3 only and Ocarina of Time seems fine in GLES3. That said I have tried very few games on my phone.

**Comment by orbea** [comment]
@loganmc10 Commit 35e137b3271c341f8d0d6e289bee5c6e96b11956 made it much worse, now instead of being broken with Super Smash Bros and GLES3, its broken with Super Smash Bros and Ocarina of Time using both GLES2 and GLES3...
```
$ git bisect good
35e137b3271c341f8d0d6e289bee5c6e96b11956 is the first bad commit
commit 35e137b3271c341f8d0d6e289bee5c6e96b11956
Author: Logan McNaughton <logan@bacoosta.com>
Date:   Fri Nov 4 07:47:40 2016 -0700

    Don't invalidate framebuffer attachments.
    
    This was put in place to be a bit of a performance hack
    It also happened to fix some driver bugs on certain devices, but it was causing some graphical glitches on Android
    For instance, the portrait in Super Smash that shows up when you go off screen had no image in it.
    
    This should probably still be implemented in GLideN64, but it needs to be implemented in the right circumstances.

:040000 040000 f41fee309de5e970763a610e79b4cb91a7880d1f c87d767fb421edead6ecbd72b406c782ab659ac5 M	custom
```

**Comment by loganmc10** [comment]
@orbea sorry I figured it would, but that commit was causing missing graphics and deviates from how GLideN64 works. It should work the same as mupen64plus FZ now 

Sometime I'll sit down in front of my Raspberry Pi and sort this out, it needs to get fixed properly

**Comment by orbea** [comment]
Alright, fair enough. I just feel like after 70 posts we made a full circle, lol.

**Comment by loganmc10** [comment]
@orbea I haven't forgotten about this issue. It's just hard for me to get time where I can have access to the TV (rapsberry pi) and the laptop at the same time to troubleshoot this...

Can you try putting:
```
glClear(GL_DEPTH_BUFFER_BIT);
```

Here:
https://github.com/loganmc10/GLupeN64/blob/master/GLideN64/src/FrameBuffer.cpp#L747

This issue is going to require a bit of testing, when I was trying to solve this on the Raspberry Pi one thing seemed to fix it, but then it turned out it would crop up in another game, etc...

**Comment by loganmc10** [comment]
With that change on the Raspberry Pi (removing the current glDiscardFramebuffer code) it is much better, but still has missing stuff from time to time, this is a very strange issue.

I am curious if that glClear makes it any better in GLES3 for you though, since the glDiscard/InvalidateFramebuffer stuff didn't seem to make any difference there.

**Comment by orbea** [comment]
@loganmc10  Your depth branch fixes it for both GLES2 and GLES3 with both Ocarina of Time and Super Smash Bros. :)

**Comment by loganmc10** [comment]
Nice, I'll need to do some testing over the next few days to make sure that this doesn't cause any regressions before I merge it.

**Comment by orbea** [comment]
That is fine, I can try some other games too. Thanks!

**Comment by loganmc10** [comment]
So far I'm pretty happy with this, I don't see any GL errors and I don't see the missing graphics in Smash Bros that I saw with the other solution, plus it seems to work for GLES3 as well.

**Comment by loganmc10** [comment]
@orbea when you get a chance on your desktop/laptop, can you see if this depth branch fixes this issue:

https://github.com/loganmc10/GLupeN64/issues/76

(missing 3&4 players in GoldenEye multiplayer)

It seems to almost solve the problem, but for me it flickers with the incorrect image every 2-3 seconds.

**Comment by loganmc10** [comment]
Ok I've merged this change into master @orbea if you could double check the master branch to make sure this solves it, then we can close this issue (again)

**Comment by loganmc10** [comment]
@orbea is this still an issue for you? The version on the libretro buildbot should have this fix (same with my buildbot)

**Comment by orbea** [comment]
Sorry for the late reply, I was distracted by other things and have not tested much yet. I tested the two games known to causes issues with both GLES2 and GLES3 and its resolved. So I will close this, thanks! :)
